CREATE OR REPLACE FORCE  VIEW "EUMOWY"."LOGIN_ROLA"
("AUW_ID","LOGIN", "ROLA")  AS
SELECT AUW_ID, AUW_LOGIN, ROL_NAZWA FROM CBD_ADM.ADM_UZYTKOWNICY_WEB auw
JOIN CBD_ADM.ADM_UZYTKOWNICY uzy on auw.AUW_UZY_ID = uzy.UZY_ID
JOIN CBD_ADM.ADM_UZYTKOWNICY_W_ROLACH uwr on uwr.UWR_UZY_ID = uzy.UZY_ID
JOIN CBD_ADM.ADM_ROLE rol on rol.ROL_ID = uwr.UWR_ROL_ID
JOIN CBD_ADM.ADM_APLIKACJE apl on apl.APL_ID = rol.ROL_APL_ID
WHERE APL_KOD = 'EUM';

grant select on LOGIN_ROLA to EUMOWY_APP;