-- new fields for representatives for address separation
ALTER TABLE EUMOWY.REPRESENTATIVE
ADD (
  STREET_TITLE VARCHAR2(4) NULL,
  STREET VARCHAR2(40) NULL,
  HOUSE_NUMBER VARCHAR2(6) NULL,
  FLAT_NUMBER VARCHAR2(4) NULL,
  CITY VARCHAR2(33) NULL,
  POSTAL_CODE VARCHAR2(6) NULL,
  POST_OFFICE VARCHAR2(33) NULL
);