package com.eservice.eumowy.enums.options

enum PosSystemSupplier {
    WIN_S_BEN_ALMAR, TRANS_PAY_TPSOFT, UTA_TRANS_TPSOFT, WINSHOP_JANTAR, SAFO_ASSECCO, MCSPAL_MC_COMP, PC_POC_JANTAR,
    KASA_REKORD, MAGISTRAT_MICOMP, EUROKARTA_UPOS, HALO2_HALO, ASERV_FORCOM, NEO_COMBO_POSNET, ELZAB_DELTAMAX,
    EUROSOFT_APTEKA_MULTI_2126, NBP, AVISTA, EUROPOS_EXORIGO, XPOS_EXREME, KASNET_NET, COMARCH_ERP, STOKROTKA,
    PETROSTATION_SYGNITY, SMALL_BUSINESS_SYMPLEX, DYNAMICS_AX_OTAGO, GASTRO_POS_SOFTECH, ITX_POS_INDITEX,
    FIS_POS_FLASHCOM_357, NAMOS_WINCOR, TOP9000_TOP, BILETOMAT_INFOBOX, MERONA, FOODSOFT, COMARCH_OPTIMA,
    EUROBILET_VECTORSOFT, PETRORETAIL, KASA_MAGNAT, MIS_SAI, GATE_WEAR, FIS_POS_FLASHCOM_460, VISTULA,
    UIDD, POSFLOW_WINCORNIXDORF, EUROSOFT_APTEKA_MULTI, AMAX_ILC
}