package com.eservice.eumowy.enums.options

enum PosSystemSupplier {
    WIN_S_BEN_ALMAR, TRANS_PAY_TPSOFT, UTA_TRANS_TPSOFT,
    WINSHOP_JANTAR, SAFO_ASSECCO, MCSPAL_MC_COMP, PC_POC_JANTAR, KASA_REKORD, MAGISTRAT_MICOMP, EXORIGO_UPOS, HALO2_HALO,
    ASERV_FORCOM, ELZAB_DELTAMAX, EUROSOFT_APTEKA_MULTI, NBP, AVISTA, EUROPOS_EXORIGO, XPOS_EXREME, KASNET_NET,
    ERP_ALTUM_COMARCH, COMARCH_ERP, STOKROTKA, PETROSTATION_SYGNITY, SMALL_BUSINESS_SYMPLEX, DYNAMICS_AX_OTAGO,
    GASTRO_POS_SOFTECH, ITX_POS_INDITEX, HIPOS, FIS_POS_FLASHCOM, NAMOS_WINCOR, TOP9000_TOP, BILETOMAT_INFOBOX,
    MERONA, FOODSOFT, COMARCH_OPTIMA, EUROBILET_VECTORSOFT, PETRORETAIL, KASA_MAGNAT, MIS_SAI, GATE_WEAR, VISTULA,
    UiDD, POSFLOW_WINCORNIXDORF, EUROSOFT_APTEKA_MULTI_2, AMAX_ILC, C3_TP_METRO, LUCAS_ORACLE, APART, GASTRO_SOFTWARE,
    ERP_COMARCH, WAPRO_ASSECO, MISAL, PC_POS_INSOFT, IZZYYREST_MERCO, KC_POC, TOPSA, SUBIEKT_INSERT, DIEBOLD_NIXDORF,
    NOATECH, M4B, INFOVER, X_SOL_BASE, OLIMP_LERIKOMP, SOFLERI_LERIKOMP, NEODETAL_NEONET, S4H, POSBISTRO, DGPARK, COMMIT,
    VENDON, SMARTSOFTWARE, POSITIVE_CINEMA, DYNAMICS_INTEGRO, HZ_SKEJ, IKORIS_SOFTCOM, RETILIA_QUICKSON, ERP_EL_ERP_SERWIS,
    PROPARK, ST, DP_MED, CCC, SOOT_KJM, SKINCONTROL, MICROS_3700, PSIPOS, CLANWILIAM, TALECH, RETAIL_SOLUTIONS,
    HYPER_DRIVE, CAPTIVA, TTSOFT, ELZAB, GTECH, MCCOMP, MUNICOM, GO_POS, BETASI, GECOS, SAFO, SYRIUSZ, STREAMSOFT,
    CHARTLINSKI, EPROJECTS, MERA, SMALL_BUSINESS, VENDO_ERP_CFI, ERP_WINCASH, INPOS, K2ONLINE, STREAMSOFT_2, MVB,
    K10_ELZAB, MINI_LT_ELZAB, JOTA_ELZAB, FAWAG_POSNET, BINGO_MAX, ERP_DIGITLAND, NEO_ONLINE_POSNET, REVO_POSNET,
    MOBILE_POSNET, ERGO_POSNET, BINGO_ONLINE, KAMSOFT, RPOS_NCR, SENTO_NOVITUS, NANO_NOVITUS, NANO2_NOVITUS,
    LINK_NOVITUS, PERFECT, ENOVA_365, VERITUM, RC_HURT, SYMFONIA, PROFIPIEK, DIEBOLD, GABOS, SAFO_ASSECO
}
