#Grails Metadata file
#Fri Feb 14 10:38:54 CET 2014
app.grails.version=2.2.3
app.name=eumowy
app.version=1.1.32
plugins.ajax-uploader=1.1
plugins.app-info=1.0.2
plugins.eclipse-scripts=1.0.7
plugins.file-uploader=1.2.1
plugins.grails-melody=1.45
plugins.gson=1.1.4
plugins.mail=1.0.1
plugins.modernizr=2.6.2
plugins.remote-pagination=0.4.4
plugins.spring-security-core=1.2.7.3
plugins.weak-ssl=1.0
