#Grails Metadata file
#Wed Jul 02 09:54:47 CEST 2014
app.grails.version=2.4.2
app.name=eumowy
app.servlet.version=3.0
app.version=1.2
plugins.app-info=1.0.2
plugins.mail=1.0.1
plugins.spring-security-core=2.0-RC3
plugins.weak-ssl=1.0
