#Grails Metadata file
#Thu Jul 18 10:43:04 CEST 2013
app.grails.version=2.2.3
app.name=eumowy
app.version=0.1
plugins.app-info=1.0.2
plugins.gson=1.1.4
plugins.mail=1.0.1
plugins.spring-security-core=1.2.7.3
plugins.weak-ssl=1.0
