<fieldset class="subpanel-fieldset">
	<legend><g:message code="panel.newpoint.additionalequipment.title" /></legend>
	<div class="subpanel-fieldset-centercontent" >
		<label for="points[${id}].additionalequipmentSameForEveryPoint"><g:checkBox name="points[${id}].additionalequipmentSameForEveryPoint" /><g:message code="panel.sameforeverypoint" /></label>
		<table class="vertical-center" >
			<tbody>
				<tr><td><g:message code="panel.newpoint.additionalequipment.pinpad" /></td><td>typ <select name="points[${id}].pinPadTyp" id="points[${id}].pinPadType" style="width: 50px"></select></td><td><g:textField name="points[${id}].pinPadIlosc" id="points[${id}].pinPadCount" style="width: 50px"/> szt.</td><td><g:textField name="points[${id}].pinPadCena" id="points[${id}].pinPadPrice" style="width: 50px"/> <g:message code="panel.price" /></td></tr>
				<tr><td><g:message code="panel.newpoint.additionalequipment.router" /></td><td>typ <select name="points[${id}].routerTyp" id="points[${id}].routerType" style="width: 50px"></select></td><td><g:textField name="points[${id}].routerIlosc" id="points[${id}].routerCount" style="width: 50px"/> szt.</td><td><g:textField name="points[${id}].routerCena" id="points[${id}].routerPrice" style="width: 50px"/> <g:message code="panel.price" /></td></tr>
				<tr><td><g:message code="panel.newpoint.additionalequipment.cardreader" /></td><td>typ <select name="points[${id}].czytnikKartTyp" id="points[${id}].cardReaderType" style="width: 50px"></select></td><td><g:textField name="points[${id}].czytnikKartIlosc" id="points[${id}].cardReaderCount" style="width: 50px"/> szt.</td><td><g:textField name="points[${id}].czytnikKartCena" id="points[${id}].cardReaderPrice" style="width: 50px"/> <g:message code="panel.price" /></td></tr>
				<tr><td><g:message code="panel.newpoint.additionalequipment.other" /> <g:textField name="points[${id}].inneWyposazenie" id="points[${id}].otherAdditionalDevice" style="width: 150px;" /> <label for="points[${id}].otherAdditionalDeviceSsl"><g:checkBox name="points[${id}].inneWyposazenieSsl" id="points[${id}].otherAdditionalDeviceSsl" /><g:message code="panel.ssl" /></label> <label for="points[${id}].otherAdditionalDeviceGprs"><g:checkBox name="points[${id}].inneWyposazenieGprs" id="points[${id}].otherAdditionalDeviceGprs" /><g:message code="panel.gprs" /></label></td><td>typ <select name="points[${id}].inneWyposazenieTyp" id="points[${id}].otherAdditionalDeviceType" style="width: 50px"></select></td><td><g:textField name="points[${id}].inneWyposazenieIlosc" id="points[${id}].otherAdditionalDeviceCount" style="width: 50px"/> szt.</td><td><g:textField name="points[${id}].inneWyposazenieCena" id="points[${id}].otherAdditionalDevicePrice" style="width: 50px"/> <g:message code="panel.price" /></td></tr>
			</tbody>
		</table>
	</div>
</fieldset>