<fieldset class="subpanel-fieldset">
	<legend><g:message code="panel.newpoint.additionalequipment.title" /></legend>
	<div class="subpanel-fieldset-centercontent" >
		<label for="points[${id}].additionalequipmentSameForEveryPoint"><g:checkBox id="points[${id}].additionalequipmentSameForEveryPoint" name="points[${id}].dodatkoweWyposazenieTakSamoDlaWszystkichPunktow" value="${pointData?.dodatkoweWyposazenieTakSamoDlaWszystkichPunktow}" /><g:message code="panel.sameforeverypoint" /></label>
		<table class="vertical-center" >
			<tbody>
				<tr><td><g:message code="panel.newpoint.additionalequipment.pinpad" /></td><td>typ <g:select name="points[${id}].pinPadTyp" id="points[${id}].pinPadType" from="[]" value="${pointData?.pinPadTyp}" style="width: 50px"></g:select></td><td><g:textField name="points[${id}].pinPadIlosc" id="points[${id}].pinPadCount" style="width: 50px" value="${pointData?.pinPadIlosc}"/> szt.</td><td><g:textField name="points[${id}].pinPadCena" id="points[${id}].pinPadPrice" style="width: 50px" value="${pointData?.pinPadCena}"/> <g:message code="panel.price" /></td></tr>
				<tr><td><g:message code="panel.newpoint.additionalequipment.router" /></td><td>typ <g:select name="points[${id}].routerTyp" id="points[${id}].routerType" from="[]" value="${pointData?.routerTyp}" style="width: 50px"></g:select></td><td><g:textField name="points[${id}].routerIlosc" id="points[${id}].routerCount" style="width: 50px" value="${pointData?.routerIlosc}"/> szt.</td><td><g:textField name="points[${id}].routerCena" id="points[${id}].routerPrice" style="width: 50px" value="${pointData?.routerCena}"/> <g:message code="panel.price" /></td></tr>
				<tr><td><g:message code="panel.newpoint.additionalequipment.cardreader" /></td><td>typ <g:select name="points[${id}].czytnikKartTyp" id="points[${id}].cardReaderType" from="[]" value="${pointData?.czytnikKartTyp}" style="width: 50px"></g:select></td><td><g:textField name="points[${id}].czytnikKartIlosc" id="points[${id}].cardReaderCount" style="width: 50px" value="${pointData?.czytnikKartIlosc}"/> szt.</td><td><g:textField name="points[${id}].czytnikKartCena" id="points[${id}].cardReaderPrice" style="width: 50px" value="${pointData?.czytnikKartCena}"/> <g:message code="panel.price" /></td></tr>
				<tr><td><g:message code="panel.newpoint.additionalequipment.other" /> <g:textField name="points[${id}].inneWyposazenie" id="points[${id}].otherAdditionalDevice" value="${pointData?.inneWyposazenie}" style="width: 150px;" /> <label for="points[${id}].otherAdditionalDeviceSsl"><g:checkBox name="points[${id}].inneWyposazenieSsl" id="points[${id}].otherAdditionalDeviceSsl" value="${pointData?.inneWyposazenieSsl}"/><g:message code="panel.ssl" /></label> <label for="points[${id}].otherAdditionalDeviceGprs"><g:checkBox name="points[${id}].inneWyposazenieGprs" id="points[${id}].otherAdditionalDeviceGprs" value="${pointData?.inneWyposazenieGprs}"/><g:message code="panel.gprs" /></label></td><td>typ <select name="points[${id}].inneWyposazenieTyp" id="points[${id}].otherAdditionalDeviceType" style="width: 50px"></select></td><td><g:textField name="points[${id}].inneWyposazenieIlosc" id="points[${id}].otherAdditionalDeviceCount" style="width: 50px" value="${pointData?.inneWyposazenieIlosc}"/> szt.</td><td><g:textField name="points[${id}].inneWyposazenieCena" id="points[${id}].otherAdditionalDevicePrice" style="width: 50px" value="${pointData?.inneWyposazenieCena}"/> <g:message code="panel.price" /></td></tr>
			</tbody>
		</table>
	</div>
</fieldset>