<div id="cardPaymentPanel">
    <fieldset style="text-align: center">
        <div class="belka-glowna"><g:message code="panel.card.payment.title"/></div>
        <div style="text-align: center; padding-top: 20px; width: 750px" class="centre">
            <table class="vertical-center">
                <thead>
                    <tr><td></td><td class="bold" style="max-width: 120px"><g:message code="panel.percent.fee.label"/></td><td  class="bold" style="max-width: 120px"><g:message code="panel.flat.rate.label"/></td></tr>
                </thead>
                <tbody>
                    <tr><td class="bold">1. <g:message code="panel.visa.ue"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">1.1 <g:message code="panel.consumer.credit.charge"/></td><td><g:textField name="card-p-1.1" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-1.1" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">1.2 <g:message code="panel.consumer.debit"/></td><td><g:textField name="card-p-1.2" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-1.2" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">1.3 <g:message code="panel.commercial.buisness"/></td><td><g:textField name="card-p-1.3" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-1.3" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="bold">2. <g:message code="panel.visa.not.ue"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">2.1 <g:message code="panel.consumer.credit.charge"/></td><td><g:textField name="card-p-2.1" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-2.1" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">2.2 <g:message code="panel.consumer.debit"/></td><td><g:textField name="card-p-2.2" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-2.2" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">2.3 <g:message code="panel.commercial.buisness"/></td><td><g:textField name="card-p-2.3" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-2.3" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="bold">3. <g:message code="panel.visa.poland"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">3.1.1 <g:message code="panel.consumer.credit.charge.to" args="['20,00']"/></td><td><g:textField name="card-p-3.1.1" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-3.1.1" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">3.1.2 <g:message code="panel.consumer.credit.charge.from" args="['20,01']"/></td><td><g:textField name="card-p-3.1.2" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-3.1.2" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">3.2.1 <g:message code="panel.consumer.debit.to" args="['20,00']"/></td><td><g:textField name="card-p-3.2.1" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-3.2.1" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">3.2.2 <g:message code="panel.consumer.debit.from" args="['20,01']"/></td><td><g:textField name="card-p-3.2.2" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-3.2.2" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="bold">4. <g:message code="panel.mastercard.ue"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">4.1 <g:message code="panel.consumer.credit"/></td><td><g:textField name="card-p-4.1" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-4.1" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">4.2 <g:message code="panel.consumer.debit"/></td><td><g:textField name="card-p-4.2" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-4.2" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">4.3 <g:message code="panel.commercial.buisness"/></td><td><g:textField name="card-p-4.3" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-4.3" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">4.4 <g:message code="panel.maestro"/></td><td><g:textField name="card-p-4.4" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-4.4" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="bold">5. <g:message code="panel.mastercard.not.ue"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">5.1 <g:message code="panel.consumer.credit"/></td><td><g:textField name="card-p-5.1" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-5.1" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">5.2 <g:message code="panel.consumer.debit"/></td><td><g:textField name="card-p-5.2" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-5.2" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">5.3 <g:message code="panel.commercial.buisness"/></td><td><g:textField name="card-p-5.3" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-5.3" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">5.4 <g:message code="panel.maestro"/></td><td><g:textField name="card-p-5.4" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-5.4" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="bold">6. <g:message code="panel.mastercard.poland"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.1.1 <g:message code="panel.consumer.credit.to" args="['20,00']"/></td><td><g:textField name="card-p-6.1.1" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-6.1.1" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.1.2 <g:message code="panel.consumer.credit.from.to" args="['20,01', '40,00']"/></td><td><g:textField name="card-p-6.1.2" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-6.1.2" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.1.3 <g:message code="panel.consumer.credit.from" args="['40,01']"/></td><td><g:textField name="card-p-6.1.3" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-6.1.3" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.2.1 <g:message code="panel.consumer.debit.to" args="['20,00']"/></td><td><g:textField name="card-p-6.2.1" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-6.2.1" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.2.2 <g:message code="panel.consumer.debit.from.to" args="['20,01','40,00']"/></td><td><g:textField name="card-p-6.2.2" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-6.2.2" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.2.3 <g:message code="panel.consumer.debit.from" args="['40,01']"/></td><td><g:textField name="card-p-6.2.3" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-6.2.3" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.4.1 <g:message code="panel.maestro.to" args="['20,00']"/>Maestro do 20,00 zł </td><td><g:textField name="card-p-6.4.1" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-6.4.1" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.4.2 <g:message code="panel.maestro.from.to" args="['20,01', '40,00']"/></td><td><g:textField name="card-p-6.4.2" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-6.4.2" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.4.3 <g:message code="panel.maestro.from" args="['40,01']"/></td><td><g:textField name="card-p-6.4.3" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-6.4.3" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="bold">7. <g:message code="panel.visa.pkopb"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">7.1.1 <g:message code="panel.consumer.credit.charge.to" args="['20,00']"/></td><td><g:textField name="card-p-7.1.1" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-7.1.1" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">7.1.2 <g:message code="panel.consumer.credit.charge.from" args="['20,01']"/></td><td><g:textField name="card-p-7.1.2" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-7.1.2" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">7.2.1 <g:message code="panel.consumer.debit.to" args="['20,00']"/></td><td><g:textField name="card-p-7.2.1" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-7.2.1" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">7.2.2 <g:message code="panel.consumer.debit.from" args="['20,01']"/></td><td><g:textField name="card-p-7.2.2" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-7.2.2" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">7.3 <g:message code="panel.commercial.buisness"/></td><td><g:textField name="card-p-7.3" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-7.3" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="bold">8. <g:message code="panel.mastercard.pkobp"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.1.1 <g:message code="panel.consumer.credit.to" args="['20,00']"/></td><td><g:textField name="card-p-8.1.1" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-8.1.1" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.1.2 <g:message code="panel.consumer.credit.from.to" args="['20,01', '40,00']"/></td><td><g:textField name="card-p-8.1.2" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-8.1.2" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.1.3 <g:message code="panel.consumer.credit.from" args="['40,01']"/></td><td><g:textField name="card-p-8.1.3" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-8.1.3" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.2.1 <g:message code="panel.consumer.debit.to" args="['20,00']"/></td><td><g:textField name="card-p-8.2.1" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-8.2.1" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.2.2 <g:message code="panel.consumer.debit.from.to" args="['20,01', '40,00']"/></td><td><g:textField name="card-p-8.2.2" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-8.2.2" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.2.3 <g:message code="panel.consumer.debit.from" args="['40,01']"/></td><td><g:textField name="card-p-8.2.3" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-8.2.3" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.3 <g:message code="panel.commercial.buisness"/></td><td><g:textField name="card-p-8.3" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-8.3" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.4.1 <g:message code="panel.maestro.to" args="['20,00']"/></td><td><g:textField name="card-p-8.4.1" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-8.4.1" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.4.2 <g:message code="panel.maestro.from.to" args="['20,01','40,00']"/></td><td><g:textField name="card-8.4.2" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-8.4.2" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.4.3 <g:message code="panel.maestro.from" args="['40,01']"/></td><td><g:textField name="card-p-8.4.3" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-8.4.3" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="bold">9. <g:message code="panel.dinersclub.upercase"/></td><td><g:textField name="card-p-9" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-9" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="bold">10. <g:message code="panel.iko"/></td><td><g:textField name="card-p-10" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:textField name="card-f-10" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                </tbody>
            </table>
        </div>
    </fieldset>
</div>