<div id="cardPaymentPanel">
    <fieldset style="text-align: center">
        <div class="belka-glowna"><g:message code="panel.card.payment.title"/></div>
        <div style="text-align: center; padding-top: 20px; width: 750px" class="centre">
            <table class="vertical-center">
                <thead>
                    <tr><td></td><td class="bold" style="max-width: 120px"><g:message code="panel.percent.fee.label"/></td><td  class="bold" style="max-width: 120px"><g:message code="panel.flat.rate.label"/></td></tr>
                </thead>
                <tbody>
                    <tr><td class="bold">1. <g:message code="panel.visa.ue"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">1.1 <g:message code="panel.consumer.credit.charge"/></td><td><g:field type="number" step="any" name="visaEUKKOPr" value="${data.visaEUKKOPr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="visaEUKKOSt" value="${data.visaEUKKOSt}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">1.2 <g:message code="panel.consumer.debit"/></td><td><g:field type="number" step="any" name="visaEUKDPr" value="${data.visaEUKDPr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="visaEUKDSt" value="${data.visaEUKDSt}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">1.3 <g:message code="panel.commercial.buisness"/></td><td><g:field type="number" step="any" name="visaEUKBPr" value="${data.visaEUKBPr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="visaEUKBSt" value="${data.visaEUKBSt}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="bold">2. <g:message code="panel.visa.not.ue"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">2.1 <g:message code="panel.consumer.credit.charge"/></td><td><g:field type="number" step="any" name="visaOutEUKKOPr" value="${data.visaOutEUKKOPr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="visaOutEUKKOSt" value="${data.visaOutEUKKOSt}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">2.2 <g:message code="panel.consumer.debit"/></td><td><g:field type="number" step="any" name="visaOutEUKDPr" value="${data.visaOutEUKDPr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="visaOutEUKDSt" value="${data.visaOutEUKDSt}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">2.3 <g:message code="panel.commercial.buisness"/></td><td><g:field type="number" step="any" name="visaOutEUKBPr" value="${data.visaOutEUKBPr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="visaOutEUKBSt" value="${data.visaOutEUKBSt}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="bold">3. <g:message code="panel.visa.poland"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">3.1.1 <g:message code="panel.consumer.credit.charge.to" args="['20,00']"/></td><td><g:field type="number" step="any" name="visaPolskaKKO1Pr" readonly="true" value="${data.visaPolskaKKO1Pr}" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="visaPolskaKKO1St" value="${data.visaPolskaKKO1St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">3.1.2 <g:message code="panel.consumer.credit.charge.from" args="['20,01']"/></td><td><g:field type="number" step="any" name="visaPolskaKKO2Pr" readonly="true" value="${data.visaPolskaKKO2Pr}" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="visaPolskaKKO2St" value="${data.visaPolskaKKO2St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">3.2.1 <g:message code="panel.consumer.debit.to" args="['20,00']"/></td><td><g:field type="number" step="any" name="visaPolskaKD1Pr" readonly="true" value="${data.visaPolskaKD1Pr}" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="visaPolskaKD1St" value="${data.visaPolskaKD1St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">3.2.2 <g:message code="panel.consumer.debit.from" args="['20,01']"/></td><td><g:field type="number" step="any" name="visaPolskaKD2Pr" readonly="true" value="${data.visaPolskaKD2Pr}" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="visaPolskaKD2St" value="${data.visaPolskaKD2St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">3.3 <g:message code="panel.commercial.buisness"/></td><td><g:field type="number" step="any" name="visaPolskaKBPr" readonly="true" value="${data.visaPolskaKBPr}" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field name="visaPolskaKBSt" value="${data.visaPolskaKBSt}" type="number" step="any" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="bold">4. <g:message code="panel.mastercard.ue"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">4.1 <g:message code="panel.consumer.credit"/></td><td><g:field type="number" step="any" name="mastercardEUKKPr" value="${data.mastercardEUKKPr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field name="mastercardEUKKSt" value="${data.mastercardEUKKSt}" type="number" step="any" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">4.2 <g:message code="panel.consumer.debit"/></td><td><g:field type="number" step="any" name="mastercardEUKDPr" value="${data.mastercardEUKDPr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field name="mastercardEUKDSt" value="${data.mastercardEUKDSt}" type="number" step="any" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">4.3 <g:message code="panel.commercial.buisness"/></td><td><g:field type="number" step="any" name="mastercardEUKBLPr" value="${data.mastercardEUKBLPr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field name="mastercardEUKBLSt" value="${data.mastercardEUKBLSt}" type="number" step="any" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">4.4 <g:message code="panel.maestro"/></td><td><g:field type="number" step="any" name="mastercardEUMPr" value="${data.mastercardEUMPr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="mastercardEUMSt" value="${data.mastercardEUMSt}" type="number" step="any" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="bold">5. <g:message code="panel.mastercard.not.ue"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">5.1 <g:message code="panel.consumer.credit"/></td><td><g:field type="number" step="any" name="mastercardOutEUKKPr" value="${data.mastercardOutEUKKPr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field name="mastercardOutEUKKSt" value="${data.mastercardOutEUKKSt}" type="number" step="any" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">5.2 <g:message code="panel.consumer.debit"/></td><td><g:field type="number" step="any" name="mastercardOutEUKDPr" value="${data.mastercardOutEUKDPr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field name="mastercardOutEUKDSt" value="${data.mastercardOutEUKDSt}" type="number" step="any" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">5.3 <g:message code="panel.commercial.buisness"/></td><td><g:field type="number" step="any" name="mastercardOutEUKBPr" value="${data.mastercardOutEUKBPr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field name="mastercardOutEUKBSt" value="${data.mastercardOutEUKBSt}" type="number" step="any" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">5.4 <g:message code="panel.maestro"/></td><td><g:field type="number" step="any" name="mastercardOutEUMPr" value="${data.mastercardOutEUMPr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field name="mastercardOutEUMSt" value="${data.mastercardOutEUMSt}" type="number" step="any" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="bold">6. <g:message code="panel.mastercard.poland"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.1.1 <g:message code="panel.consumer.credit.to" args="['20,00']"/></td><td><g:field type="number" step="any" name="mastercardPolskaKK1Pr" value="${data.mastercardPolskaKK1Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="mastercardPolskaKK1St" value="${data.mastercardPolskaKK1St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.1.2 <g:message code="panel.consumer.credit.from.to" args="['20,01', '40,00']"/></td><td><g:field type="number" step="any" name="mastercardPolskaKK2Pr" value="${data.mastercardPolskaKK2Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="mastercardPolskaKK2St" value="${data.mastercardPolskaKK2St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.1.3 <g:message code="panel.consumer.credit.from" args="['40,01']"/></td><td><g:field type="number" step="any" name="mastercardPolskaKK3Pr" value="${data.mastercardPolskaKK3Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="mastercardPolskaKK3St" value="${data.mastercardPolskaKK3St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.2.1 <g:message code="panel.consumer.debit.to" args="['20,00']"/></td><td><g:field type="number" step="any" name="mastercardPolskaKD1Pr" value="${data.mastercardPolskaKD1Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="mastercardPolskaKD1St" value="${data.mastercardPolskaKD1St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.2.2 <g:message code="panel.consumer.debit.from.to" args="['20,01','40,00']"/></td><td><g:field type="number" step="any" name="mastercardPolskaKD2Pr" value="${data.mastercardPolskaKD2Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="mastercardPolskaKD2St" value="${data.mastercardPolskaKD2St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.2.3 <g:message code="panel.consumer.debit.from" args="['40,01']"/></td><td><g:field type="number" step="any" name="mastercardPolskaKD3Pr" value="${data.mastercardPolskaKD3Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="mastercardPolskaKD3St" value="${data.mastercardPolskaKD3St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.3 <g:message code="panel.consumer.debit.business"/></td><td><g:field type="number" step="any" name="mastercardPolskaKBPr" value="${data.mastercardPolskaKBPr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="mastercardPolskaKBSt" value="${data.mastercardPolskaKBSt}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.4.1 <g:message code="panel.maestro.to" args="['20,00']"/>Maestro do 20,00 zł </td><td><g:field type="number" step="any" name="mastercardPolskaM1Pr" value="${data.mastercardPolskaM1Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="mastercardPolskaM1St" value="${data.mastercardPolskaM1St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.4.2 <g:message code="panel.maestro.from.to" args="['20,01', '40,00']"/></td><td><g:field type="number" step="any" name="mastercardPolskaM2Pr" value="${data.mastercardPolskaM2Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="mastercardPolskaM2St" value="${data.mastercardPolskaM2St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.4.3 <g:message code="panel.maestro.from" args="['40,01']"/></td><td><g:field type="number" step="any" name="mastercardPolskaM3Pr" value="${data.mastercardPolskaM3Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="mastercardPolskaM1St" value="${data.mastercardPolskaM3St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="bold">7. <g:message code="panel.visa.pkopb"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">7.1.1 <g:message code="panel.consumer.credit.charge.to" args="['20,00']"/></td><td><g:field type="number" step="any" name="visaPKOBPKKO1Pr" value="${data.visaPKOBPKKO1Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="visaPKOBPKKO1St" value="${data.visaPKOBPKKO1St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">7.1.2 <g:message code="panel.consumer.credit.charge.from" args="['20,01']"/></td><td><g:field type="number" step="any" name="visaPKOBPKKO2Pr" value="${data.visaPKOBPKKO2Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="visaPKOBPKKO2St" value="${data.visaPKOBPKKO2St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">7.2.1 <g:message code="panel.consumer.debit.to" args="['20,00']"/></td><td><g:field type="number" step="any" name="visaPKOBPKD1Pr" value="${data.visaPKOBPKD1Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="visaPKOBPKD1St" value="${data.visaPKOBPKD1St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">7.2.2 <g:message code="panel.consumer.debit.from" args="['20,01']"/></td><td><g:field type="number" step="any" name="visaPKOBPKD2Pr" value="${data.visaPKOBPKD2Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="visaPKOBPKD2St" value="${data.visaPKOBPKD2St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">7.3 <g:message code="panel.commercial.buisness"/></td><td><g:field type="number" step="any" name="visaPKOBPKB3Pr" value="${data.visaPKOBPKB3Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="visaPKOBPKB3St" value="${data.visaPKOBPKB3St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="bold">8. <g:message code="panel.mastercard.pkobp"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.1.1 <g:message code="panel.consumer.credit.to" args="['20,00']"/></td><td><g:field type="number" step="any" name="mastercardPKOBPKK1Pr" value="${data.mastercardPKOBPKK1Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="mastercardPKOBPKK1St" value="${data.mastercardPKOBPKK1St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.1.2 <g:message code="panel.consumer.credit.from.to" args="['20,01', '40,00']"/></td><td><g:field type="number" step="any" name="mastercardPKOBPKK2Pr" value="${data.mastercardPKOBPKK2Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="mastercardPKOBPKK2St" value="${data.mastercardPKOBPKK2St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.1.3 <g:message code="panel.consumer.credit.from" args="['40,01']"/></td><td><g:field type="number" step="any" name="mastercardPKOBPKK3Pr" value="${data.mastercardPKOBPKK3Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="mastercardPKOBPKK3St" value="${data.mastercardPKOBPKK3St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.2.1 <g:message code="panel.consumer.debit.to" args="['20,00']"/></td><td><g:field type="number" step="any" name="mastercardPKOBPKD1Pr" value="${data.mastercardPKOBPKD1Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="mastercardPKOBPKD1St" value="${data.mastercardPKOBPKD1St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.2.2 <g:message code="panel.consumer.debit.from.to" args="['20,01', '40,00']"/></td><td><g:field type="number" step="any" name="mastercardPKOBPKD2LPr" value="${data.mastercardPKOBPKD2LPr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="mastercardPKOBPKD2LSt" value="${data.mastercardPKOBPKD2LSt}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.2.3 <g:message code="panel.consumer.debit.from" args="['40,01']"/></td><td><g:field type="number" step="any" name="mastercardPKOBPKD3Pr" value="${data.mastercardPKOBPKD3Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="mastercardPKOBPKD3St" value="${data.mastercardPKOBPKD3St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.3 <g:message code="panel.commercial.buisness"/></td><td><g:field type="number" step="any" name="mastercardPKOBPKBPr" value="${data.mastercardPKOBPKBPr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="card_f_8_3" value="${data.mastercardPKOBPKBSt}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.4.1 <g:message code="panel.maestro.to" args="['20,00']"/></td><td><g:field type="number" step="any" name="mastercardPKOBPM1Pr" value="${data.mastercardPKOBPM1Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="mastercardPKOBPM1St" value="${data.mastercardPKOBPM1St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.4.2 <g:message code="panel.maestro.from.to" args="['20,01','40,00']"/></td><td><g:field type="number" step="any" name="mastercardPKOBPM2Pr" value="${data.mastercardPKOBPM2Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="mastercardPKOBPM2St" value="${data.mastercardPKOBPM2St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.4.3 <g:message code="panel.maestro.from" args="['40,01']"/></td><td><g:field type="number" step="any" name="mastercardPKOBPM3Pr" value="${data.mastercardPKOBPM3Pr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td><g:field type="number" step="any" name="mastercardPKOBPM3St" value="${data.mastercardPKOBPM3St}" readonly="true" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                    <tr><td class="bold">9. <g:message code="panel.dinersclub.upercase"/></td><td><g:field type="number" step="any" name="dinersClubPr" value="${data.dinersClubPr}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td></td></tr>
                    <tr><td class="bold">10. <g:message code="panel.iko"/></td><td><g:field type="number" step="any" name="ikoPr" value="${data.ikoSt}" readonly="true" style="width: 50px"/> <g:message code="panel.percent"/></td><td></td></tr>
                </tbody>
            </table>
        </div>
    </fieldset>
</div>