<div id="cardPaymentPanel">
    <fieldset style="text-align: center">
        <div class="belka-glowna"><g:message code="panel.card.payment.title"/></div>
        <div style="text-align: center; padding-top: 20px; width: 800px" class="centre">
            <table class="vertical-center">
                <thead>
                    <tr><td></td><td class="bold" style=" text-align: center"><g:message code="panel.percent.fee.label"/></td><td  class="bold" style=" text-align: center"><g:message code="panel.flat.rate.label"/></td></tr>
                </thead>
                <tbody>
                    <tr><td class="bold">1. <g:message code="panel.visa.ue"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">1.1 <g:message code="panel.consumer.credit.charge"/></td><td><eumowy:percentageField validatable="${data}"  name="visaEUKKOPr" value="${data.visaEUKKOPr}" readonly="true" /> </td><td><eumowy:currencyField class="float-number" validatable="${data}"  name="visaEUKKOSt" value="${data.visaEUKKOSt}" /></td></tr>
                    <tr><td class="cardPaymentPanel-padding">1.2 <g:message code="panel.consumer.debit"/></td><td><eumowy:percentageField   name="visaEUKDPr" value="${data.visaEUKDPr}" readonly="true" /> </td><td><eumowy:currencyField class="float-number" validatable="${data}"  name="visaEUKDSt" value="${data.visaEUKDSt}" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">1.3 <g:message code="panel.commercial.buisness"/></td><td><eumowy:percentageField validatable="${data}"  name="visaEUKBPr" value="${data.visaEUKBPr}" readonly="true" /> </td><td><eumowy:currencyField class="float-number" validatable="${data}"  name="visaEUKBSt" value="${data.visaEUKBSt}" /> </td></tr>
                    <tr><td class="bold">2. <g:message code="panel.visa.not.ue"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">2.1 <g:message code="panel.consumer.credit.charge"/></td><td><eumowy:percentageField validatable="${data}"  name="visaOutEUKKOPr" value="${data.visaOutEUKKOPr}" readonly="true" /> </td><td><eumowy:currencyField class="float-number" validatable="${data}"  name="visaOutEUKKOSt" value="${data.visaOutEUKKOSt}" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">2.2 <g:message code="panel.consumer.debit"/></td><td><eumowy:percentageField validatable="${data}"  name="visaOutEUKDPr" value="${data.visaOutEUKDPr}" readonly="true" /> </td><td><eumowy:currencyField class="float-number" validatable="${data}"  name="visaOutEUKDSt" value="${data.visaOutEUKDSt}" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">2.3 <g:message code="panel.commercial.buisness"/></td><td><eumowy:percentageField validatable="${data}"  name="visaOutEUKBPr" value="${data.visaOutEUKBPr}" readonly="true" /> </td><td><eumowy:currencyField class="float-number" validatable="${data}"  name="visaOutEUKBSt" value="${data.visaOutEUKBSt}" /> </td></tr>
                    <tr><td class="bold">3. <g:message code="panel.visa.poland"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">3.1.1 <g:message code="panel.consumer.credit.charge.to" args="['20,00']"/></td><td><eumowy:percentageField validatable="${data}"  name="visaPolskaKKO1Pr" readonly="true" value="${data.visaPolskaKKO1Pr}" /> </td><td><eumowy:currencyField validatable="${data}"  name="visaPolskaKKO1St" value="${data.visaPolskaKKO1St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">3.1.2 <g:message code="panel.consumer.credit.charge.from" args="['20,01']"/></td><td><eumowy:percentageField validatable="${data}"  name="visaPolskaKKO2Pr" readonly="true" value="${data.visaPolskaKKO2Pr}" /> </td><td><eumowy:currencyField validatable="${data}"  name="visaPolskaKKO2St" value="${data.visaPolskaKKO2St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">3.2.1 <g:message code="panel.consumer.debit.to" args="['20,00']"/></td><td><eumowy:percentageField validatable="${data}"  name="visaPolskaKD1Pr" readonly="true" value="${data.visaPolskaKD1Pr}" /> </td><td><eumowy:currencyField validatable="${data}"  name="visaPolskaKD1St" value="${data.visaPolskaKD1St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">3.2.2 <g:message code="panel.consumer.debit.from" args="['20,01']"/></td><td><eumowy:percentageField validatable="${data}"  name="visaPolskaKD2Pr" readonly="true" value="${data.visaPolskaKD2Pr}" /> </td><td><eumowy:currencyField validatable="${data}"  name="visaPolskaKD2St" value="${data.visaPolskaKD2St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">3.3 <g:message code="panel.commercial.buisness"/></td><td><eumowy:percentageField validatable="${data}"  name="visaPolskaKBPr" readonly="true" value="${data.visaPolskaKBPr}" /> </td><td><eumowy:currencyField class="float-number" validatable="${data}" name="visaPolskaKBSt" value="${data.visaPolskaKBSt}"  /> </td></tr>
                    <tr><td class="bold">4. <g:message code="panel.mastercard.ue"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">4.1 <g:message code="panel.consumer.credit"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardEUKKPr" value="${data.mastercardEUKKPr}" readonly="true" /> </td><td><eumowy:currencyField class="float-number" validatable="${data}" name="mastercardEUKKSt" value="${data.mastercardEUKKSt}"  /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">4.2 <g:message code="panel.consumer.debit"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardEUKDPr" value="${data.mastercardEUKDPr}" readonly="true" /> </td><td><eumowy:currencyField class="float-number" validatable="${data}" name="mastercardEUKDSt" value="${data.mastercardEUKDSt}"  /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">4.3 <g:message code="panel.commercial.buisness"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardEUKBLPr" value="${data.mastercardEUKBLPr}" readonly="true" /> </td><td><eumowy:currencyField class="float-number" validatable="${data}" name="mastercardEUKBLSt" value="${data.mastercardEUKBLSt}"  /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">4.4 <g:message code="panel.maestro"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardEUMPr" value="${data.mastercardEUMPr}" readonly="true" /> </td><td><eumowy:currencyField class="float-number" validatable="${data}"  name="mastercardEUMSt" value="${data.mastercardEUMSt}"  /> </td></tr>
                    <tr><td class="bold">5. <g:message code="panel.mastercard.not.ue"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">5.1 <g:message code="panel.consumer.credit"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardOutEUKKPr" value="${data.mastercardOutEUKKPr}" readonly="true" /> </td><td><eumowy:currencyField class="float-number" validatable="${data}" name="mastercardOutEUKKSt" value="${data.mastercardOutEUKKSt}"  /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">5.2 <g:message code="panel.consumer.debit"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardOutEUKDPr" value="${data.mastercardOutEUKDPr}" readonly="true" /> </td><td><eumowy:currencyField class="float-number" validatable="${data}" name="mastercardOutEUKDSt" value="${data.mastercardOutEUKDSt}"  /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">5.3 <g:message code="panel.commercial.buisness"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardOutEUKBPr" value="${data.mastercardOutEUKBPr}" readonly="true" /> </td><td><eumowy:currencyField class="float-number" validatable="${data}" name="mastercardOutEUKBSt" value="${data.mastercardOutEUKBSt}"  /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">5.4 <g:message code="panel.maestro"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardOutEUMPr" value="${data.mastercardOutEUMPr}" readonly="true" /> </td><td><eumowy:currencyField class="float-number" validatable="${data}" name="mastercardOutEUMSt" value="${data.mastercardOutEUMSt}"  /> </td></tr>
                    <tr><td class="bold">6. <g:message code="panel.mastercard.poland"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.1.1 <g:message code="panel.consumer.credit.to" args="['20,00']"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardPolskaKK1Pr" value="${data.mastercardPolskaKK1Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="mastercardPolskaKK1St" value="${data.mastercardPolskaKK1St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.1.2 <g:message code="panel.consumer.credit.from.to" args="['20,01', '40,00']"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardPolskaKK2Pr" value="${data.mastercardPolskaKK2Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="mastercardPolskaKK2St" value="${data.mastercardPolskaKK2St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.1.3 <g:message code="panel.consumer.credit.from" args="['40,01']"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardPolskaKK3Pr" value="${data.mastercardPolskaKK3Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="mastercardPolskaKK3St" value="${data.mastercardPolskaKK3St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.2.1 <g:message code="panel.consumer.debit.to" args="['20,00']"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardPolskaKD1Pr" value="${data.mastercardPolskaKD1Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="mastercardPolskaKD1St" value="${data.mastercardPolskaKD1St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.2.2 <g:message code="panel.consumer.debit.from.to" args="['20,01','40,00']"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardPolskaKD2Pr" value="${data.mastercardPolskaKD2Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="mastercardPolskaKD2St" value="${data.mastercardPolskaKD2St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.2.3 <g:message code="panel.consumer.debit.from" args="['40,01']"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardPolskaKD3Pr" value="${data.mastercardPolskaKD3Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="mastercardPolskaKD3St" value="${data.mastercardPolskaKD3St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.3 <g:message code="panel.commercial.buisness"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardPolskaKBPr" value="${data.mastercardPolskaKBPr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="mastercardPolskaKBSt" value="${data.mastercardPolskaKBSt}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.4.1 <g:message code="panel.maestro.to" args="['20,00']"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardPolskaM1Pr" value="${data.mastercardPolskaM1Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="mastercardPolskaM1St" value="${data.mastercardPolskaM1St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.4.2 <g:message code="panel.maestro.from.to" args="['20,01', '40,00']"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardPolskaM2Pr" value="${data.mastercardPolskaM2Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="mastercardPolskaM2St" value="${data.mastercardPolskaM2St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">6.4.3 <g:message code="panel.maestro.from" args="['40,01']"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardPolskaM3Pr" value="${data.mastercardPolskaM3Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="mastercardPolskaM3St" value="${data.mastercardPolskaM3St}" readonly="true" /> </td></tr>
                    <tr><td class="bold">7. <g:message code="panel.visa.pkopb"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">7.1.1 <g:message code="panel.consumer.credit.charge.to" args="['20,00']"/></td><td><eumowy:percentageField validatable="${data}"  name="visaPKOBPKKO1Pr" value="${data.visaPKOBPKKO1Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="visaPKOBPKKO1St" value="${data.visaPKOBPKKO1St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">7.1.2 <g:message code="panel.consumer.credit.charge.from" args="['20,01']"/></td><td><eumowy:percentageField validatable="${data}"  name="visaPKOBPKKO2Pr" value="${data.visaPKOBPKKO2Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="visaPKOBPKKO2St" value="${data.visaPKOBPKKO2St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">7.2.1 <g:message code="panel.consumer.debit.to" args="['20,00']"/></td><td><eumowy:percentageField validatable="${data}"  name="visaPKOBPKD1Pr" value="${data.visaPKOBPKD1Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="visaPKOBPKD1St" value="${data.visaPKOBPKD1St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">7.2.2 <g:message code="panel.consumer.debit.from" args="['20,01']"/></td><td><eumowy:percentageField validatable="${data}"  name="visaPKOBPKD2Pr" value="${data.visaPKOBPKD2Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="visaPKOBPKD2St" value="${data.visaPKOBPKD2St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">7.3 <g:message code="panel.commercial.buisness"/></td><td><eumowy:percentageField validatable="${data}"  name="visaPKOBPKB3Pr" value="${data.visaPKOBPKB3Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="visaPKOBPKB3St" value="${data.visaPKOBPKB3St}" readonly="true" /> </td></tr>
                    <tr><td class="bold">8. <g:message code="panel.mastercard.pkobp"/></td><td></td><td></td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.1.1 <g:message code="panel.consumer.credit.to" args="['20,00']"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardPKOBPKK1Pr" value="${data.mastercardPKOBPKK1Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="mastercardPKOBPKK1St" value="${data.mastercardPKOBPKK1St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.1.2 <g:message code="panel.consumer.credit.from.to" args="['20,01', '40,00']"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardPKOBPKK2Pr" value="${data.mastercardPKOBPKK2Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="mastercardPKOBPKK2St" value="${data.mastercardPKOBPKK2St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.1.3 <g:message code="panel.consumer.credit.from" args="['40,01']"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardPKOBPKK3Pr" value="${data.mastercardPKOBPKK3Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="mastercardPKOBPKK3St" value="${data.mastercardPKOBPKK3St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.2.1 <g:message code="panel.consumer.debit.to" args="['20,00']"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardPKOBPKD1Pr" value="${data.mastercardPKOBPKD1Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="mastercardPKOBPKD1St" value="${data.mastercardPKOBPKD1St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.2.2 <g:message code="panel.consumer.debit.from.to" args="['20,01', '40,00']"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardPKOBPKD2LPr" value="${data.mastercardPKOBPKD2LPr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="mastercardPKOBPKD2LSt" value="${data.mastercardPKOBPKD2LSt}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.2.3 <g:message code="panel.consumer.debit.from" args="['40,01']"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardPKOBPKD3Pr" value="${data.mastercardPKOBPKD3Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="mastercardPKOBPKD3St" value="${data.mastercardPKOBPKD3St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.3 <g:message code="panel.commercial.buisness"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardPKOBPKBPr" value="${data.mastercardPKOBPKBPr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="mastercardPKOBPKBSt" value="${data.mastercardPKOBPKBSt}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.4.1 <g:message code="panel.maestro.to" args="['20,00']"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardPKOBPM1Pr" value="${data.mastercardPKOBPM1Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="mastercardPKOBPM1St" value="${data.mastercardPKOBPM1St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.4.2 <g:message code="panel.maestro.from.to" args="['20,01','40,00']"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardPKOBPM2Pr" value="${data.mastercardPKOBPM2Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="mastercardPKOBPM2St" value="${data.mastercardPKOBPM2St}" readonly="true" /> </td></tr>
                    <tr><td class="cardPaymentPanel-padding">8.4.3 <g:message code="panel.maestro.from" args="['40,01']"/></td><td><eumowy:percentageField validatable="${data}"  name="mastercardPKOBPM3Pr" value="${data.mastercardPKOBPM3Pr}" readonly="true" /> </td><td><eumowy:currencyField validatable="${data}"  name="mastercardPKOBPM3St" value="${data.mastercardPKOBPM3St}" readonly="true" /> </td></tr>
                    <tr><td class="bold">9. <g:message code="panel.dinersclub.upercase"/></td><td><eumowy:percentageField   name="dinersClubPr" value="${data.dinersClubPr}" readonly="true"/> </td><td></td></tr>
                    <tr><td class="bold">10. <g:message code="panel.iko"/></td><td><eumowy:percentageField  name="ikoPr" value="${data.ikoPr}" readonly="true"/> </td><td></td></tr>
                </tbody>
            </table>
        </div>
    </fieldset>
</div>