<div id="posUsagePanel">
    <fieldset style="text-align: center">
        <div class="belka-glowna"><g:message code="panel.pos.usage.title"/></div>
        <div style="text-align: center; padding-top: 20px; width: 800px" class="centre">
            <div>
                <table class="vertical-center" >
                    <thead>
                        <tr><td></td><td></td><td></td><td></td><td colspan="2"  style="text-align: center;"><g:message code="panel.used.fees"/></td><td colspan="2"  style="text-align: center;"><g:message code="panel.preferential.rate"/></td></tr>
                        <tr><td></td><td></td><td></td><td></td><td><g:message code="panel.term.price.per.month"/></td><td><g:message code="panel.pp.price.per.month"/></td><td><g:message code="panel.term.price.per.month"/></td><td><g:message code="panel.pp.price.per.month"/></td></tr>
                    </thead>
                    <tbody>
                        <tr><td><g:message code="panel.type"/> <select style="width: 50px"></select></td><td style="text-align: right;"><g:message code="panel.dialup"/></td><td><g:textField name="posDialupCount" style="width: 50px"/> <g:message code="panel.unit"/></td><td><g:textField name="posDialupPPCount" style="width: 50px"/> <g:message code="panel.pp.unit"/></td><td><g:textField name="posDialupPrice" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:textField name="posDialupPPPrice" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:textField name="posDialupPrice" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:textField name="posDialupPPPrice" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                        <tr><td><g:message code="panel.type"/> <select style="width: 50px"></select></td><td style="text-align: right;"><g:message code="panel.vpn"/></td><td><g:textField name="posVpnCount" style="width: 50px"/> <g:message code="panel.unit"/></td><td><g:textField name="posVpnPPCount" style="width: 50px"/> <g:message code="panel.pp.unit"/></td><td><g:textField name="posVpnPrice" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:textField name="posVpnPPPrice" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:textField name="posDialupPrice" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:textField name="posDialupPPPrice" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                        <tr><td><g:message code="panel.type"/> <select style="width: 50px"></select></td><td style="text-align: right;"><g:message code="panel.ssl"/></td><td><g:textField name="posSslCount" style="width: 50px"/> <g:message code="panel.unit"/></td><td><g:textField name="posSslPPCount" style="width: 50px"/> <g:message code="panel.pp.unit"/></td><td><g:textField name="posSslPrice" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:textField name="posSslPPPrice" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:textField name="posDialupPrice" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:textField name="posDialupPPPrice" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                        <tr><td><g:message code="panel.type"/> <select style="width: 50px"></select></td><td style="text-align: right;"><g:message code="panel.wifi"/></td><td><g:textField name="posWifiCount" style="width: 50px"/> <g:message code="panel.unit"/></td><td><g:textField name="posWifiPPCount" style="width: 50px"/> <g:message code="panel.pp.unit"/></td><td><g:textField name="posWifiPrice" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:textField name="posWifiPPPrice" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:textField name="posDialupPrice" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:textField name="posDialupPPPrice" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                        <tr><td><g:message code="panel.type"/> <select style="width: 50px"></select></td><td style="text-align: right;"><g:message code="panel.gprs"/></td><td><g:textField name="posGprsCount" style="width: 50px"/> <g:message code="panel.unit"/></td><td><g:textField name="posGprsPPCount" style="width: 50px"/> <g:message code="panel.pp.unit"/></td><td><g:textField name="posGprsPrice" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:textField name="posGprsPPPrice" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:textField name="posDialupPrice" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:textField name="posDialupPPPrice" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                        <tr><td></td><td style="text-align: right;"><g:message code="panel.base"/></td><td><g:textField name="baseCount" style="width: 50px"/> <g:message code="panel.unit"/> </td><td></td><td></td><td></td><td></td><td></td></tr>
                    </tbody>
                </table>
            </div>
        </div>
    </fieldset>
</div>