<fieldset class="subpanel-fieldset" style="clear: both;">
	<legend><g:message code="panel.newpos.posset.title" /></legend>
	<div class="subpanel-fieldset-centercontent" style="width: 800px;" >
		<label for="${panelType}[${id}].possetforselectedpointSameForEveryPoint"><g:checkBox id="${panelType}[${id}].possetforselectedpointSameForEveryPoint" name="${panelType}[${id}].zestawPosTakSamoDlaWszystkichPunktow" value="${pointData?.zestawPosTakSamoDlaWszystkichPunktow}" /><g:message code="panel.sameforeverypoint" /></label>
		<table class="vertical-center" style="width: 800px;" >
			<thead>
				<tr><td></td><td></td><td></td><td></td><td colspan="2"  style="text-align: center;">Cena</td></tr>
				<tr><td></td><td></td><td></td><td></td><td>Term./mies</td><td>PP./mies.</td></tr>
			</thead>
			<tbody>
				<tr><td>typ <dict:typeSelect nip="${nip}"  medium="DIALUP" id="${panelType}[${id}].possetDialupType" name="${panelType}[${id}].dialupTyp" from="[]" valueMessagePrefix="" value="${pointData?.dialupTyp}"  style="width: 220px"/></td><td style="text-align: right;"><g:message code="panel.dialup" /></td><td><eumowy:textField name="${panelType}[${id}].dialupIlosc" id="${panelType}[${id}].dialupCount" value="${pointData?.dialupIlosc}" style="width: 50px"/> szt.</td><td><eumowy:textField name="${panelType}[${id}].dialupPPIlosc" id="${panelType}[${id}].dialupPPCount" value="${pointData?.dialupPPIlosc}" style="width: 50px"/> PP. szt.</td><td><eumowy:textField name="${panelType}[${id}].dialupCena" id="${panelType}[${id}].dialupPrice" value="${pointData?.dialupCena}" style="width: 50px"/> zł.</td><td><eumowy:textField name="${panelType}[${id}].dialupPPCena" id="${panelType}[${id}].dialupPPPrice" value="${pointData?.dialupPPCena}" style="width: 50px"/> zł.</td></tr>
				<tr><td>typ <dict:typeSelect nip="${nip}"  medium="VPN" id="${panelType}[${id}].possetVpnType" name="${panelType}[${id}].vpnTyp" from="[]" valueMessagePrefix="" value="${pointData?.vpnTyp}"  style="width: 220px"/></td><td style="text-align: right;"><g:message code="panel.vpn" /></td><td><eumowy:textField name="${panelType}[${id}].vpnIlosc" id="${panelType}[${id}].vpnCount" value="${pointData?.vpnIlosc}" style="width: 50px"/> szt.</td><td><eumowy:textField name="${panelType}[${id}].vpnPPIlosc" id="${panelType}[${id}].vpnPPCount" value="${pointData?.vpnPPIlosc}" style="width: 50px"/> PP. szt.</td><td><eumowy:textField name="${panelType}[${id}].vpnCena" id="${panelType}[${id}].vpnPrice" value="${pointData?.vpnCena}" style="width: 50px"/> zł.</td><td><eumowy:textField name="${panelType}[${id}].vpnPPCena" id="${panelType}[${id}].vpnPPPrice" value="${pointData?.vpnPPCena}" style="width: 50px"/> zł.</td></tr>
				<tr><td>typ <dict:typeSelect nip="${nip}"  medium="SSL" id="${panelType}[${id}].possetSslType" name="${panelType}[${id}].sslTyp" from="[]" valueMessagePrefix="" value="${pointData?.sslTyp}"  style="width: 220px"/></td><td style="text-align: right;"><g:message code="panel.ssl" /></td><td><eumowy:textField name="${panelType}[${id}].sslIlosc" id="${panelType}[${id}].sslCount" value="${pointData?.sslIlosc}" style="width: 50px"/> szt.</td><td><eumowy:textField name="${panelType}[${id}].sslPPIlosc" id="${panelType}[${id}].sslPPCount" value="${pointData?.sslPPIlosc}" style="width: 50px"/> PP. szt.</td><td><eumowy:textField name="${panelType}[${id}].sslCena" id="${panelType}[${id}].sslPrice" value="${pointData?.sslCena}" style="width: 50px"/> zł.</td><td><eumowy:textField name="${panelType}[${id}].sslPPCena" id="${panelType}[${id}].sslPPPrice" value="${pointData?.sslPPCena}" style="width: 50px"/> zł.</td></tr>
				<tr><td>typ <dict:typeSelect nip="${nip}"  medium="WiFI" id="${panelType}[${id}].possetWifiType" name="${panelType}[${id}].wifiTyp" from="[]" valueMessagePrefix="" value="${pointData?.wifiTyp}"  style="width: 220px"/></td><td style="text-align: right;"><g:message code="panel.wifi" /></td><td><eumowy:textField name="${panelType}[${id}].wifiIlosc" id="${panelType}[${id}].wifiCount" value="${pointData?.wifiIlosc}" style="width: 50px"/> szt.</td><td><eumowy:textField name="${panelType}[${id}].wifiPPIlosc" id="${panelType}[${id}].wifiPPCount" value="${pointData?.wifiPPIlosc}" style="width: 50px"/> PP. szt.</td><td><eumowy:textField name="${panelType}[${id}].wifiCena" id="${panelType}[${id}].wifiPrice" value="${pointData?.wifiCena}" style="width: 50px"/> zł.</td><td><eumowy:textField name="${panelType}[${id}].wifiPPCena" id="${panelType}[${id}].wifiPPPrice" value="${pointData?.wifiPPCena}" style="width: 50px"/> zł.</td></tr>
				<tr><td>typ <dict:typeSelect nip="${nip}"  medium="GPRS" id="${panelType}[${id}].possetGprsType" name="${panelType}[${id}].gprsTyp" from="[]" valueMessagePrefix="" value="${pointData?.gprsTyp}"  style="width: 220px"/></td><td style="text-align: right;"><g:message code="panel.gprs" /></td><td><eumowy:textField name="${panelType}[${id}].gprsIlosc" id="${panelType}[${id}].gprsCount" value="${pointData?.gprsIlosc}" style="width: 50px"/> szt.</td><td><eumowy:textField name="${panelType}[${id}].gprsPPIlosc" id="${panelType}[${id}].gprsPPCount" value="${pointData?.gprsPPIlosc}" style="width: 50px"/> PP. szt.</td><td><eumowy:textField name="${panelType}[${id}].gprsCena" id="${panelType}[${id}].gprsPrice" value="${pointData?.gprsCena}" style="width: 50px"/> zł.</td><td><eumowy:textField name="${panelType}[${id}].gprsPPCena" id="${panelType}[${id}].gprsPPPrice" value="${pointData?.gprsPPCena}" style="width: 50px"/> zł.</td></tr>
				<tr><td></td><td style="text-align: right;"><g:message code="panel.base" /></td><td><eumowy:textField id="${panelType}[${id}].baseCount" name="${panelType}[${id}].bazaIlosc" value="${pointData?.bazaIlosc}" style="width: 50px"/> szt.</td><td></td><td></td><td></td></tr>
			</tbody>
		</table>
	</div>
</fieldset>