<div id="posUsagePanel">
    <fieldset style="text-align: center">
        <div class="belka-glowna"><g:message code="panel.pos.usage.title"/></div>
        <div style="text-align: center; padding-top: 20px; width: 800px" class="centre">
            <div>
                <table class="vertical-center" >
                    <thead>
                        <tr><td></td><td></td><td></td><td></td><td colspan="2"  style="text-align: center;"><g:message code="panel.used.fees"/></td><td colspan="2"  style="text-align: center;"><g:message code="panel.preferential.rate"/></td></tr>
                        <tr><td></td><td></td><td></td><td></td><td><g:message code="panel.term.price.per.month"/></td><td><g:message code="panel.pp.price.per.month"/></td><td><g:message code="panel.term.price.per.month"/></td><td><g:message code="panel.pp.price.per.month"/></td></tr>
                    </thead>
                    <tbody>
                        <tr><td><g:message code="panel.type"/> <dict:typeSelect nip="${nip}" name="oplPOSDialUpTyp" value="${data.oplPOSDialUpTyp}" /></td><td style="text-align: right;"><g:message code="panel.dialup"/></td><td><g:field name="oplPOSDialUpIlosc" type="number" value="${data.oplPOSDialUpIlosc}" style="width: 50px"/> <g:message code="panel.unit"/></td><td><g:field type="number" name="oplPOSDialUpIloscPP" value="${data.oplPOSDialUpIloscPP}" style="width: 50px"/> <g:message code="panel.pp.unit"/></td><td><g:field type="number" step="any"  name="oplPOSDialUpNormalneMies" value="${data.oplPOSDialUpNormalneMies}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="number" step="any"  type="number" step="any"  name="oplPOSDialUpNormalnePP" value="${data.oplPOSDialUpNormalnePP}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="number" step="any"  type="number" step="any"  name="oplPOSDialUpPreferencyjneMies" value="${data.oplPOSDialUpPreferencyjneMies}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="number" step="any"  type="number" step="any"  name="oplPOSDialUpPreferencyjnePP" value="${data.oplPOSDialUpPreferencyjnePP}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                        <tr><td><g:message code="panel.type"/> <dict:typeSelect nip="${nip}" name="oplPOSVPNTyp" value="${data.oplPOSVPNTyp}" /></td><td style="text-align: right;"><g:message code="panel.vpn"/></td><td><g:field name="oplPOSVPNIlosc" type="number" value="${data.oplPOSVPNIlosc}" style="width: 50px"/> <g:message code="panel.unit"/></td><td><g:field type="number" name="oplPOSVPNIloscPP" value="${data.oplPOSVPNIloscPP}" style="width: 50px"/> <g:message code="panel.pp.unit"/></td><td><g:field type="number" step="any"  name="oplPOSVPNNormalneMies" value="${data.oplPOSVPNNormalneMies}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="number" step="any"  name="oplPOSVPNNormalnePP" value="${data.oplPOSVPNNormalnePP}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="number" step="any"  name="oplPOSVPNPreferencyjneMies" value="${data.oplPOSVPNPreferencyjneMies}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="number" step="any"  name="oplPOSVPNPreferencyjnePP" value="${data.oplPOSVPNPreferencyjnePP}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                        <tr><td><g:message code="panel.type"/> <dict:typeSelect nip="${nip}" name="oplPOSSSLTyp" value="${data.oplPOSSSLTyp}" /></td><td style="text-align: right;"><g:message code="panel.ssl"/></td><td><g:field name="oplPOSSSLIlosc" type="number" value="${data.oplPOSSSLIlosc}" style="width: 50px"/> <g:message code="panel.unit"/></td><td><g:field type="number" name="oplPOSSSLIloscPP" value="${data.oplPOSSSLIloscPP}" style="width: 50px"/> <g:message code="panel.pp.unit"/></td><td><g:field type="number" step="any"  name="oplPOSSSLNormalneMies" value="${data.oplPOSSSLNormalneMies}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="number" step="any"  name="oplPOSSSLNormalnePP" value="${data.oplPOSSSLNormalnePP}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="number" step="any"  name="oplPOSSSLPreferencyjneMies" value="${data.oplPOSSSLPreferencyjneMies}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="number" step="any"  name="oplPOSSSLPreferencyjnePP" value="${data.oplPOSSSLPreferencyjnePP}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                        <tr><td><g:message code="panel.type"/> <dict:typeSelect nip="${nip}" name="oplPOSWiFiTyp" value="${data.oplPOSWiFiTyp}" /></td><td style="text-align: right;"><g:message code="panel.wifi"/></td><td><g:field name="oplPOSWiFiIlosc" type="number" value="${data.oplPOSWiFiIlosc}" style="width: 50px"/> <g:message code="panel.unit"/></td><td><g:field type="number" name="oplPOSWiFiIloscPP" value="${data.oplPOSWiFiIloscPP}" style="width: 50px"/> <g:message code="panel.pp.unit"/></td><td><g:field type="number" step="any"  name="oplPOSWiFiNormalneMies" value="${data.oplPOSWiFiNormalneMies}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="number" step="any"  name="oplPOSWiFiNormalnePP" value="${data.oplPOSWiFiNormalnePP}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="number" step="any"  name="oplPOSWiFiPreferencyjneMies" value="${data.oplPOSWiFiPreferencyjneMies}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="number" step="any"  name="oplPOSWiFiPreferencyjnePP" value="${data.oplPOSWiFiPreferencyjnePP}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                        <tr><td><g:message code="panel.type"/> <dict:typeSelect nip="${nip}" name="oplPOSGPRSTyp" value="${data.oplPOSGPRSTyp}" /></td><td style="text-align: right;"><g:message code="panel.gprs"/></td><td><g:field name="oplPOSGPRSIlosc" type="number" value="${data.oplPOSGPRSIlosc}" style="width: 50px"/> <g:message code="panel.unit"/></td><td><g:field type="number" name="oplPOSGPRSIloscPP" value="${data.oplPOSGPRSIloscPP}" style="width: 50px"/> <g:message code="panel.pp.unit"/></td><td><g:field type="number" step="any"  name="oplPOSGPRSNormalneMies" value="${data.oplPOSGPRSNormalneMies}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="number" step="any"  name="oplPOSGPRSNormalnePP" value="${data.oplPOSGPRSNormalnePP}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="number" step="any"  name="oplPOSGPRSPreferencyjneMies" value="${data.oplPOSGPRSPreferencyjneMies}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="number" step="any"  name="oplPOSGPRSPreferencyjnePP" value="${data.oplPOSGPRSPreferencyjnePP}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                        <tr><td></td><td style="text-align: right;"><g:message code="panel.base"/></td><td><g:field name="baseCount" type="number" value="${data.oplPOSBaza}" style="width: 50px"/> <g:message code="panel.unit"/> </td><td></td><td></td><td></td><td></td><td></td></tr>
                    </tbody>
                </table>
            </div>
        </div>
    </fieldset>
</div>