<div id="posUsagePanel">
    <fieldset style="text-align: center">
        <div class="belka-glowna"><g:message code="panel.pos.usage.title"/></div>
        <div style="text-align: center; padding-top: 20px;" class="centre">
            <div>
                <g:hiddenField name="isZestawPosOdplatneUzywanieShown" value="tak"/>
                <table class="vertical-center" >
                    <thead>
                        <tr><td></td><td></td><td></td><td></td><td colspan="2"  style="text-align: center;"><g:message code="panel.used.fees"/></td><td colspan="2"  style="text-align: center;"><g:message code="panel.preferential.rate"/></td></tr>
                        <tr><td></td><td></td><td></td><td></td><td><g:message code="panel.term.price.per.month"/></td><td><g:message code="panel.pp.price.per.month"/></td><td><g:message code="panel.term.price.per.month"/></td><td><g:message code="panel.pp.price.per.month"/></td></tr>
                    </thead>
                    <tbody>
                        <tr><td><g:message code="panel.type"/> <dict:typeSelect id="oplPOSDialUpTyp"  medium="DIALUP" nip="${nip}" name="oplPOSDialUpTyp" value="${data.oplPOSDialUpTyp}" style="width: 220px"/></td><td style="text-align: right;"><g:message code="panel.dialup"/></td><td><g:field name="oplPOSDialUpIlosc" type="text" class="integer-number" value="${data.oplPOSDialUpIlosc}" style="width: 50px"/> <g:message code="panel.unit"/></td><td><g:field type="text" class="integer-number" name="oplPOSDialUpIloscPP" value="${data.oplPOSDialUpIloscPP}" style="width: 50px"/> <g:message code="panel.pp.unit"/></td><td><g:field type="text" name="oplPOSDialUpNormalneMies" value="${data.oplPOSDialUpNormalneMies}" class = "float-number" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="text" class="float-number" name="oplPOSDialUpNormalnePP" value="${data.oplPOSDialUpNormalnePP}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="text" class="float-number" name="oplPOSDialUpPreferencyjneMies" value="${data.oplPOSDialUpPreferencyjneMies}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="text" class="float-number"  name="oplPOSDialUpPreferencyjnePP" value="${data.oplPOSDialUpPreferencyjnePP}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                        <tr><td><g:message code="panel.type"/> <dict:typeSelect id="oplPOSVPNTyp"  medium="VPN" nip="${nip}" name="oplPOSVPNTyp" value="${data.oplPOSVPNTyp}" style="width: 220px" /></td><td style="text-align: right;"><g:message code="panel.vpn"/></td><td><g:field name="oplPOSVPNIlosc" type="text" class="integer-number" value="${data.oplPOSVPNIlosc}" style="width: 50px"/> <g:message code="panel.unit"/></td><td><g:field type="text" class="integer-number" name="oplPOSVPNIloscPP" value="${data.oplPOSVPNIloscPP}" style="width: 50px"/> <g:message code="panel.pp.unit"/></td><td><g:field type="text"  name="oplPOSVPNNormalneMies" value="${data.oplPOSVPNNormalneMies}" class="float-number" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="text" class="float-number" name="oplPOSVPNNormalnePP" value="${data.oplPOSVPNNormalnePP}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="text" class="float-number"  name="oplPOSVPNPreferencyjneMies" value="${data.oplPOSVPNPreferencyjneMies}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="text" class="float-number"  name="oplPOSVPNPreferencyjnePP" value="${data.oplPOSVPNPreferencyjnePP}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                        <tr><td><g:message code="panel.type"/> <dict:typeSelect id="oplPOSSSLTyp"  medium="SSL" nip="${nip}" name="oplPOSSSLTyp" value="${data.oplPOSSSLTyp}" style="width: 220px" /></td><td style="text-align: right;"><g:message code="panel.ssl"/></td><td><g:field name="oplPOSSSLIlosc" type="text" class="integer-number" value="${data.oplPOSSSLIlosc}" style="width: 50px"/> <g:message code="panel.unit"/></td><td><g:field type="text" class="integer-number" name="oplPOSSSLIloscPP" value="${data.oplPOSSSLIloscPP}" style="width: 50px"/> <g:message code="panel.pp.unit"/></td><td><g:field type="text" class="float-number" name="oplPOSSSLNormalneMies" value="${data.oplPOSSSLNormalneMies}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="text" class="float-number" name="oplPOSSSLNormalnePP" value="${data.oplPOSSSLNormalnePP}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="text" class="float-number"  name="oplPOSSSLPreferencyjneMies" value="${data.oplPOSSSLPreferencyjneMies}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="text" class="float-number"  name="oplPOSSSLPreferencyjnePP" value="${data.oplPOSSSLPreferencyjnePP}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                        <tr><td><g:message code="panel.type"/> <dict:typeSelect id="oplPOSWiFiTyp"  medium="WiFi" nip="${nip}" name="oplPOSWiFiTyp" value="${data.oplPOSWiFiTyp}" style="width: 220px" /></td><td style="text-align: right;"><g:message code="panel.wifi"/></td><td><g:field name="oplPOSWiFiIlosc" type="text" class="integer-number" value="${data.oplPOSWiFiIlosc}" style="width: 50px"/> <g:message code="panel.unit"/></td><td><g:field type="text" class="integer-number" name="oplPOSWiFiIloscPP" value="${data.oplPOSWiFiIloscPP}" style="width: 50px"/> <g:message code="panel.pp.unit"/></td><td><g:field type="text" class="float-number" name="oplPOSWiFiNormalneMies" value="${data.oplPOSWiFiNormalneMies}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="text" class="float-number" name="oplPOSWiFiNormalnePP" value="${data.oplPOSWiFiNormalnePP}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="text" class="float-number"  name="oplPOSWiFiPreferencyjneMies" value="${data.oplPOSWiFiPreferencyjneMies}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="text" class="float-number" name="oplPOSWiFiPreferencyjnePP" value="${data.oplPOSWiFiPreferencyjnePP}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                        <tr><td><g:message code="panel.type"/> <dict:typeSelect id="oplPOSGPRSTyp"  medium="GPRS" nip="${nip}" name="oplPOSGPRSTyp" value="${data.oplPOSGPRSTyp}" style="width: 220px" /></td><td style="text-align: right;"><g:message code="panel.gprs"/></td><td><g:field name="oplPOSGPRSIlosc" type="text" class="integer-number" value="${data.oplPOSGPRSIlosc}" style="width: 50px"/> <g:message code="panel.unit"/></td><td><g:field type="text" class="integer-number" name="oplPOSGPRSIloscPP" value="${data.oplPOSGPRSIloscPP}" style="width: 50px"/> <g:message code="panel.pp.unit"/></td><td><g:field type="text" class="float-number" name="oplPOSGPRSNormalneMies" value="${data.oplPOSGPRSNormalneMies}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="text" class="float-number" name="oplPOSGPRSNormalnePP" value="${data.oplPOSGPRSNormalnePP}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="text" class="float-number"  name="oplPOSGPRSPreferencyjneMies" value="${data.oplPOSGPRSPreferencyjneMies}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td><td><g:field type="text" class="float-number" name="oplPOSGPRSPreferencyjnePP" value="${data.oplPOSGPRSPreferencyjnePP}" style="width: 50px"/> <g:message code="panel.polish.currency"/></td></tr>
                        <tr id="trBase"><td></td><td style="text-align: right;"><g:message code="panel.base"/></td><td><g:field id="oplPOSBaza" name="oplPOSBaza" type="text" class="integer-number" value="${data.oplPOSBaza}" style="width: 50px"/> <g:message code="panel.unit"/> </td><td></td><td></td><td></td><td></td><td></td></tr>
                    </tbody>
                </table>
            </div>
        </div>
    </fieldset>
</div>

<r:script>
    jQuery(document).ready(function() {
        jQuery("#oplPOSGPRSTyp").change(verifyBaseVisibility)
        verifyBaseVisibility()
    });

    function verifyBaseVisibility(){
        var value = jQuery("#oplPOSGPRSTyp").val().toString()
        if(value == "Verifone Vx670 GPRS"){
            jQuery("#trBase").show()
        }
        else{
            jQuery("#trBase").hide()
        }
    }
</r:script>
