INSERT INTO EUMOWY.PANEL (ID, VERSION, NAME, ORDER_NO)
VALUES (EUMOWY.PANEL_SEQ.nextval, 0, 'oplataZaRaportowanieKAS', 315);

INSERT INTO EUMOWY.SIGNATURE_PANEL(ID, VERSION, PANEL_ID, SIGNATURE_ID)
VALUES (
        EUMOWY.SIGNATURE_PANEL_SEQ.nextval,
        0,
        (SELECT ID FROM EUMOWY.PANEL WHERE NAME = 'oplataZaRaportowanieKAS'),
        (SELECT ID FROM EUMOWY.SIGNATURE WHERE NAME = 'virtualNowaUmowa')
);