INSERT INTO EUMOWY.PANEL (ID, VERSION, NAME, ORDER_NO)
VALUES (EUMOWY.PANEL_SEQ.nextval, 0, 'oplataZaRaportowanieKAS', 315);

INSERT INTO EUMOWY.SIGNATURE_PANEL(ID, VERSION, PANEL_ID, SIGNATURE_ID)
VALUES (
        EUMOWY.SIGNATURE_PANEL_SEQ.nextval,
        0,
        (SELECT ID FROM EUMOWY.PANEL WHERE NAME = 'oplataZaRaportowanieKAS'),
        (SELECT ID FROM EUMOWY.SIGNATURE WHERE NAME = 'virtualNowaUmowa')
);

-- Fixy do ESEU-325

INSERT INTO EUMOWY.SIGNATURE_PANEL(ID, VERSION, PANEL_ID, SIGNATURE_ID)
VALUES (
   EUMOWY.SIGNATURE_PANEL_SEQ.nextval,
   0,
   (SELECT ID FROM EUMOWY.PANEL WHERE NAME = 'oplataZaRaportowanieKAS'),
   (SELECT ID FROM EUMOWY.SIGNATURE WHERE NAME = 'AP/UPZT1/1.010/24-08-01')
);

INSERT INTO EUMOWY.SIGNATURE_PANEL(ID, VERSION, PANEL_ID, SIGNATURE_ID)
VALUES (
   EUMOWY.SIGNATURE_PANEL_SEQ.nextval,
   0,
   (SELECT ID FROM EUMOWY.PANEL WHERE NAME = 'oplataZaRaportowanieKAS'),
   (SELECT ID FROM EUMOWY.SIGNATURE WHERE NAME = 'AP/UPZT2/1.010/24-08-01')
);

INSERT INTO EUMOWY.SIGNATURE_PANEL(ID, VERSION, PANEL_ID, SIGNATURE_ID)
VALUES (
   EUMOWY.SIGNATURE_PANEL_SEQ.nextval,
   0,
   (SELECT ID FROM EUMOWY.PANEL WHERE NAME = 'oplataZaRaportowanieKAS'),
   (SELECT ID FROM EUMOWY.SIGNATURE WHERE NAME = 'AP/UPZT3/1.010/24-08-01')
);

INSERT INTO EUMOWY.SIGNATURE_PANEL(ID, VERSION, PANEL_ID, SIGNATURE_ID)
VALUES (
   EUMOWY.SIGNATURE_PANEL_SEQ.nextval,
   0,
   (SELECT ID FROM EUMOWY.PANEL WHERE NAME = 'oplataZaRaportowanieKAS'),
   (SELECT ID FROM EUMOWY.SIGNATURE WHERE NAME = 'AP/UPZT4/1.010/24-08-01')
);

INSERT INTO EUMOWY.SIGNATURE_PANEL(ID, VERSION, PANEL_ID, SIGNATURE_ID)
VALUES (
   EUMOWY.SIGNATURE_PANEL_SEQ.nextval,
   0,
   (SELECT ID FROM EUMOWY.PANEL WHERE NAME = 'oplataZaRaportowanieKAS'),
   (SELECT ID FROM EUMOWY.SIGNATURE WHERE NAME = 'AP/UPZ/ZSNT1/1.007/24-08-01')
);

INSERT INTO EUMOWY.SIGNATURE_PANEL(ID, VERSION, PANEL_ID, SIGNATURE_ID)
VALUES (
   EUMOWY.SIGNATURE_PANEL_SEQ.nextval,
   0,
   (SELECT ID FROM EUMOWY.PANEL WHERE NAME = 'oplataZaRaportowanieKAS'),
   (SELECT ID FROM EUMOWY.SIGNATURE WHERE NAME = 'AP/UPZ/ZSNT2/1.007/24-08-01')
);

INSERT INTO EUMOWY.SIGNATURE_PANEL(ID, VERSION, PANEL_ID, SIGNATURE_ID)
VALUES (
   EUMOWY.SIGNATURE_PANEL_SEQ.nextval,
   0,
   (SELECT ID FROM EUMOWY.PANEL WHERE NAME = 'oplataZaRaportowanieKAS'),
   (SELECT ID FROM EUMOWY.SIGNATURE WHERE NAME = 'AP/UPZ/ZSNT3/1.006/24-08-01')
);

INSERT INTO EUMOWY.SIGNATURE_PANEL(ID, VERSION, PANEL_ID, SIGNATURE_ID)
VALUES (
   EUMOWY.SIGNATURE_PANEL_SEQ.nextval,
   0,
   (SELECT ID FROM EUMOWY.PANEL WHERE NAME = 'oplataZaRaportowanieKAS'),
   (SELECT ID FROM EUMOWY.SIGNATURE WHERE NAME = 'AP/UPZ/ZSNT4/1.006/24-08-01')
);
