UPDATE SIGNATURE SET SHOULD_BE_MERGED = 1 WHERE NAME = 'AP/FDP/2.001/21-07-26';
UPDATE SIGNATURE SET ACTIVE = 1 WHERE NAME = 'AP/FDP/2.000/21-07-26';

DELETE FROM ACTIVITY_SIGNATURES
WHERE activity_id = (SELECT id FROM ACTIVITY WHERE code = 'dodatkowyPunkt')
  AND signature_id = (SELECT id FROM SIGNATURE WHERE name = 'AP/FDP/2.000/21-07-26');

UPDATE SIGNATURE SET ACTIVE = 1 WHERE NAME = 'AP/FDP/2.000/21-07-26';
DELETE FROM ACTIVITY_SIGNATURES
WHERE activity_id = (SELECT id FROM ACTIVITY WHERE code = 'nowaUmowa')
  AND signature_id = (SELECT id FROM SIGNATURE WHERE name = 'AP/FDP/2.001/21-07-26');
