-- dev model
create table EUMOWY.LOGS (login varchar2(255 char), log_date varchar2(255 char), log_message varchar2(255 char));
CREATE TABLE EUMOWY.KALKULATORTYPURZADZEN ( TYP VARCHAR2(50 char), SLOWNIK VARCHAR2(50 char), SMT_ID NUMBER(10,0), ID NUMBER(10,0));
CREATE TABLE EUMOWY.MAPOWANIEKALKULATORA ( POLEKALKULATOR VARCHAR2(255 char),POLEAPREEL VARCHAR2(255 char),DZIALANIE VARCHAR2(20 char));