create table EUMOWY.LOGS (login varchar2(255 char), log_date varchar2(255 char), log_message varchar2(255 char));

CREATE TABLE EUMOWY.KALKULATORTYPURZADZEN (
    TYP VARCHAR2(50 BYTE),
    SLOWNIK VARCHAR2(50 BYTE));

CREATE TABLE EUMOWY.MAPOWANIEKALKULATORA (
  POLEKALKULATOR VARCHAR2(255 BYTE),
  POLEAPREEL     VARCHAR2(255 BYTE),
  DZIALANIE      VARCHAR2(20 BYTE));