-- dev model
create table EUMOWY.LOGS (login varchar2(255 char), log_date varchar2(255 char), log_message varchar2(255 char));
CREATE TABLE EUMOWY.KALKULATORTYPURZADZEN ( TYP VARCHAR2(50 char), SLOWNIK VARCHAR2(50 char), SMT_ID NUMBER(10,0), ID NUMBER(10,0));
CREATE TABLE EUMOWY.MAPOWANIEKALKULATORA ( POLEKALKULATOR VARCHAR2(255 char),POLEAPREEL VARCHAR2(255 char),DZIALANIE VARCHAR2(20 char));
CREATE TABLE EUMOWY.EUM_SYGNATURA_FUNKCJA ( ESF_MAP_ID NUMBER NOT NULL ENABLE, ESF_SYGNATURA     VARCHAR2(255 BYTE), ESF_NAZWA_SERWISU VARCHAR2(255 BYTE), ESF_NAZWA_FUNKCJI VARCHAR2(255 BYTE), ESF_KOLEJNOSC NUMBER, ESF_ADRES_SERWISU VARCHAR2(255 BYTE), CONSTRAINT PK_EUM_SYGNATURA_FUNKCJA PRIMARY KEY (ESF_MAP_ID));