SELECT SALUTATION , NAME , SURNAME,  POSITION, COUNTRY_CODE, PESEL, BIRTH_COUNTRY, BIRTH_DATE, ID_NUMBER, ID_ISSUE_DATE,
       ID_EXPIRATION_DATE, CITIZENSHIP, STREET, STREET_TITLE, HOUSE_NUMBER, FLAT_NUMBER, CITY, POSTAL_CODE, POST_OFFICE,
       COUNTRY, EMAIL, LANDLINE_PHONE, MOBILE_PHONE, CONTRACT_SIGNED FROM EUMOWY.REPRESENTATIVE_CBD_DATA WHERE REPRESENTATIVE_ID = :id
