import { Translation } from 'primeng/api';

export const primeNgPolishTranslation: Translation = {
  accept: 'Tak',
  reject: 'Nie',
  choose: 'Wybierz',
  upload: 'Prześlij',
  cancel: 'Anuluj',
  clear: 'Wyczyść',
  apply: 'Zastosuj',
  today: 'Dzisiaj',
  weekHeader: 'Tydz.',
  dayNames: ['niedziela', 'poniedziałek', 'wtorek', 'środa', 'czwartek', 'piątek', 'sobota'],
  dayNamesShort: ['niedz.', 'pon.', 'wt.', 'śr.', 'czw.', 'pt.', 'sob.'],
  dayNamesMin: ['N', 'P', 'W', 'Ś', 'C', 'P', 'S'],
  monthNames: [
    'styczeń',
    'luty',
    'marzec',
    'kwiecień',
    'maj',
    'czerwiec',
    'lipiec',
    'sierpień',
    'wrzesień',
    'październik',
    'listopad',
    'grudzień'
  ],
  monthNamesShort: ['sty', 'lut', 'mar', 'kwi', 'maj', 'cze', 'lip', 'sie', 'wrz', 'paź', 'lis', 'gru'],
  dateFormat: 'dd.mm.yy',
  firstDayOfWeek: 1,
  emptyMessage: 'Brak danych',
  emptyFilterMessage: 'Brak wyników',
  emptySearchMessage: 'Nie znaleziono wyników',
  noFileChosenMessage: 'Nie wybrano pliku',
  passwordPrompt: 'Wprowadź hasło',
  selectionMessage: '{0} wybrano',
  emptySelectionMessage: 'Brak zaznaczenia',
  searchMessage: 'Dostępne są {0} wyniki',
  aria: {
    trueLabel: 'Prawda',
    falseLabel: 'Fałsz',
    nullLabel: 'Brak wartości',
    star: '1 gwiazdka',
    stars: '{star} gwiazdki',
    selectAll: 'Zaznacz wszystko',
    unselectAll: 'Odznacz wszystko',
    close: 'Zamknij',
    previous: 'Poprzedni',
    next: 'Następny',
    navigation: 'Nawigacja',
    scrollTop: 'Przewiń do góry',
    moveTop: 'Przenieś na początek',
    moveUp: 'Przenieś wyżej',
    moveDown: 'Przenieś niżej',
    moveBottom: 'Przenieś na koniec',
    moveToTarget: 'Przenieś do celu',
    moveToSource: 'Przenieś do źródła',
    moveAllToTarget: 'Przenieś wszystko do celu',
    moveAllToSource: 'Przenieś wszystko do źródła'
  }
};
