-- informacjeDodatkowe dla AP/UPZT
INSERT INTO EUMOWY.SIGNATURE_PANEL (ID,VERSION,PANEL_ID,SIGNATURE_ID)
VALUES (EUMOWY.SIGNATURE_PANEL_SEQ.nextval, 0, 
        (SELECT ID FROM EUMOWY.PANEL p WHERE p.NAME = 'informacjeDodatkowe'), 
        (SELECT ID FROM EUMOWY.SIGNATURE s WHERE s.NAME = 'AP/UPZT1/1.009/22-09-01'));

INSERT INTO EUMOWY.SIGNATURE_PANEL (ID,VERSION,PANEL_ID,SIGNATURE_ID)
VALUES (EUMOWY.SIGNATURE_PANEL_SEQ.nextval, 0,
        (SELECT ID FROM EUMOWY.PANEL p WHERE p.NAME = 'informacjeDodatkowe'),
        (SELECT ID FROM EUMOWY.SIGNATURE s WHERE s.NAME = 'AP/UPZT2/1.009/22-09-01'));

INSERT INTO EUMOWY.SIGNATURE_PANEL (ID,VERSION,PANEL_ID,SIGNATURE_ID)
VALUES (EUMOWY.SIGNATURE_PANEL_SEQ.nextval, 0,
        (SELECT ID FROM EUMOWY.PANEL p WHERE p.NAME = 'informacjeDodatkowe'),
        (SELECT ID FROM EUMOWY.SIGNATURE s WHERE s.NAME = 'AP/UPZT3/1.009/22-09-01'));

INSERT INTO EUMOWY.SIGNATURE_PANEL (ID,VERSION,PANEL_ID,SIGNATURE_ID)
VALUES (EUMOWY.SIGNATURE_PANEL_SEQ.nextval, 0,
        (SELECT ID FROM EUMOWY.PANEL p WHERE p.NAME = 'informacjeDodatkowe'),
        (SELECT ID FROM EUMOWY.SIGNATURE s WHERE s.NAME = 'AP/UPZT4/1.009/22-09-01'));

-- panele AML dla AP/UPZ/ZSNT3/1.005/21-01-01
INSERT INTO EUMOWY.SIGNATURE_PANEL (ID,VERSION,PANEL_ID,SIGNATURE_ID)
VALUES (EUMOWY.SIGNATURE_PANEL_SEQ.nextval, 0,
        (SELECT ID FROM EUMOWY.PANEL p WHERE p.NAME = 'informacjeDodatkowe'),
        (SELECT ID FROM EUMOWY.SIGNATURE s WHERE s.NAME = 'AP/UPZ/ZSNT3/1.005/21-01-01'));

INSERT INTO EUMOWY.SIGNATURE_PANEL (ID,VERSION,PANEL_ID,SIGNATURE_ID)
VALUES (EUMOWY.SIGNATURE_PANEL_SEQ.nextval, 0,
        (SELECT ID FROM EUMOWY.PANEL p WHERE p.NAME = 'osobaUprawnionaDoPodpisaniaUmowy'),
        (SELECT ID FROM EUMOWY.SIGNATURE s WHERE s.NAME = 'AP/UPZ/ZSNT3/1.005/21-01-01'));

-- panele AML dla AP/UPZ/ZSNT4/1.006/21-01-01
INSERT INTO EUMOWY.SIGNATURE_PANEL (ID,VERSION,PANEL_ID,SIGNATURE_ID)
VALUES (EUMOWY.SIGNATURE_PANEL_SEQ.nextval, 0,
        (SELECT ID FROM EUMOWY.PANEL p WHERE p.NAME = 'informacjeDodatkowe'),
        (SELECT ID FROM EUMOWY.SIGNATURE s WHERE s.NAME = 'AP/UPZ/ZSNT4/1.006/21-01-01'));

INSERT INTO EUMOWY.SIGNATURE_PANEL (ID,VERSION,PANEL_ID,SIGNATURE_ID)
VALUES (EUMOWY.SIGNATURE_PANEL_SEQ.nextval, 0,
        (SELECT ID FROM EUMOWY.PANEL p WHERE p.NAME = 'osobaUprawnionaDoPodpisaniaUmowy'),
        (SELECT ID FROM EUMOWY.SIGNATURE s WHERE s.NAME = 'AP/UPZ/ZSNT4/1.006/21-01-01'));

-- panele AML dla AP/UW/PON/1.004/21-01-01
INSERT INTO EUMOWY.SIGNATURE_PANEL (ID,VERSION,PANEL_ID,SIGNATURE_ID)
VALUES (EUMOWY.SIGNATURE_PANEL_SEQ.nextval, 0,
        (SELECT ID FROM EUMOWY.PANEL p WHERE p.NAME = 'informacjeDodatkowe'),
        (SELECT ID FROM EUMOWY.SIGNATURE s WHERE s.NAME = 'AP/UW/PON/1.004/21-01-01'));

INSERT INTO EUMOWY.SIGNATURE_PANEL (ID,VERSION,PANEL_ID,SIGNATURE_ID)
VALUES (EUMOWY.SIGNATURE_PANEL_SEQ.nextval, 0,
        (SELECT ID FROM EUMOWY.PANEL p WHERE p.NAME = 'osobaUprawnionaDoPodpisaniaUmowy'),
        (SELECT ID FROM EUMOWY.SIGNATURE s WHERE s.NAME = 'AP/UW/PON/1.004/21-01-01'));
