-- CREATE TABLES
create table EUMOWY.APP_PARAMETERS (id number(19,0) not null, name varchar2(255 char) unique, value varchar2(512 char), primary key (id));
create table EUMOWY.ACTIVITY (id number(19,0) not null, version number(19,0) not null, code varchar2(255 char) unique, numer_pozycji number(10,0) unique, primary key (id));
create table EUMOWY.ACTIVITY_SIGNATURES (id number(19,0) not null, version number(19,0) not null, activity_id number(19,0), mandatory number(1,0) not null, number_of_list number(10,0), signature_id number(19,0), primary key (id));
create table EUMOWY.ATTACHMENT (id number(19,0) not null, date_created timestamp not null, filename varchar2(255 char), last_updated timestamp not null, process_id number(19,0), attachments_idx number(10,0), primary key (id));
create table EUMOWY.ATTACHMENT_CONTENT (id integer not null, version integer not null, attachment_id integer not null unique, content BLOB not null, primary key (id));
create table EUMOWY.CALCFIELD (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) unique, primary key (id));
create table EUMOWY.CALCFIELD_SIGNATURE (id number(19,0) not null, version number(19,0) not null, calc_field_id number(19,0), signature_id number(19,0), primary key (id));
create table EUMOWY.CLIENT (id number(19,0) not null, version number(19,0) not null, cbd_id varchar2(255 char) unique, name varchar2(255 char) unique, nip varchar2(255 char) unique, primary key (id));
create table EUMOWY.DOCUMENT (id number(19,0) not null, date_created timestamp not null, filename varchar2(255 char), last_updated timestamp not null, pages_count integer, process_id number(19,0), documents_idx number(10,0), primary key (id));
create table EUMOWY.DOCUMENT_CONTENT (id number(19,0) not null, version number(19,0) not null, content blob not null, document_id number(19,0) not null unique, primary key (id));
create table EUMOWY.EMAIL_TEMPLATES (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char), recipent varchar2(255 char), sender varchar2(255 char), primary key (id));
create table EUMOWY.PANEL (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) unique, order_no number(10,0), primary key (id));
create table EUMOWY.POINT (id number(19,0) not null, version number(19,0) not null, cbd_id integer not null, postal_code varchar(255) not null, city varchar(255) not null, nip varchar(255) not null, home_number integer not null, flat_number integer not null, post_office varchar(255) not null, process_id number(19,0), street varchar(255) not null, primary key (id));
create table EUMOWY.POINT_DETAILS (id number(19,0) not null, version number(19,0) not null, contact_address_street_type varchar(255) not null, dataforprinting_address_street_type varchar(255) not null, mcc_code varchar(255) not null, contact_at_point_email varchar(255) not null, contact_at_point_fax varchar(255) not null, contact_at_point_first_name varchar(255) not null, contact_at_point_last_name varchar(255) not null, contact_at_point_mobile_phone varchar(255) not null, contact_at_point_phone varchar(255) not null, bank_account_number varchar(255) not null, contact_address_postal_code varchar(255) not null, contact_address_home_number integer not null, contact_address_flat_number integer not null, contact_address_post_office varchar(255) not null, contact_address_address_street varchar(255) not null, contact_address_city varchar(255) not null, bank_name varchar(255) not null, point_name_for_printing_from_POS_terminal varchar(255) not null, point_name_for_search_engine varchar(255) not null, nip varchar(255) not null, business_care decimal(19,2) not null, service_care1 decimal(19,2) not null, service_care2 decimal(19,2) not null, service_care3 decimal(19,2) not null, ph_gain decimal(19,2) not null, point_id number(19,0) not null unique, bussiness_type_in_practice varchar(255) not null, dataforprinting_address_postal_code varchar(255) not null, other_data_for_printing_from_terminal1 varchar(255) not null, other_data_for_printing_from_terminal2 varchar(255) not null, dataforprinting_address_city varchar(255) not null, dataforprinting_address_home_number integer not null, dataforprinting_address_flat_number integer not null, dataforprinting_address_post_office varchar(255) not null, dataforprinting_address_street varchar(255) not null, primary key (id));
create table EUMOWY.POS (id number(19,0) not null, version number(19,0) not null, is_selected boolean not null, date_to timestamp not null, date_from timestamp not null, pos_set_number integer not null, point_id number(19,0), price_count decimal(19,2) not null, primary key (id));
create table EUMOWY.POS_DETAILS (id number(19,0) not null, version number(19,0) not null, static_device_ip varchar(255) not null, set_analysis boolean not null, base_count integer not null, noreturnfunction boolean not null, static_device_gateway varchar(255) not null, card_reader_price decimal(19,2) not null, card_reader_count integer not null, card_reader_type varchar(255) not null, dialup_price decimal(19,2) not null, dialup_count integer not null, dialup_pp_price decimal(19,2) not null, dialup_pp_count integer not null, dialup_type varchar(255) not null, gprs_price decimal(19,2) not null, gprs_count integer not null, gprs_pp_price decimal(19,2) not null, gprs_pp_count integer not null, gprs_type varchar(255) not null, dynamic_device_support_name varchar(255) not null, static_device_support_contact_name varchar(255) not null, other_additional_device varchar(255) not null, other_additional_device_price decimal(19,2) not null, other_additional_device_gprs boolean not null, other_additional_device_count integer not null, other_additional_device_ssl boolean not null, other_additional_device_type varchar(255) not null, cash_machine_system_integration boolean not null, gift_card boolean not null, dynamic_device_support_contact varchar(255) not null, static_device_support_contact varchar(255) not null, logging_before_every_transaction boolean not null, loggin_every_change boolean not null, static_device_mask varchar(255) not null, tip1 boolean not null, dynamic_device_support_surname varchar(255) not null, static_device_support_contact_surname varchar(255) not null, pin_pad_price decimal(19,2) not null, pin_pad_count integer not null, pin_pad_type varchar(255) not null, planned_installation_date timestamp not null, pos_id number(19,0) not null unique, preauthorization boolean not null, router_price decimal(19,2) not null, router_count integer not null, router_type varchar(255) not null, ssl_price decimal(19,2) not null, ssl_count integer not null, ssl_pp_price decimal(19,2) not null, ssl_pp_count integer not null, ssl_type varchar(255) not null, teleKodzik boolean not null, telePompka boolean not null, additional_notes varchar(255) not null, vpn_price decimal(19,2) not null, vpn_count integer not null, vpn_pp_price decimal(19,2) not null, vpn_pp_count integer not null, vpn_type varchar(255) not null, wifi_price decimal(19,2) not null, wifi_count integer not null, wifi_pp_price decimal(19,2) not null, wifi_pp_count integer not null, wifi_type varchar(255) not null, day_close_to timestamp not null, day_close_from timestamp not null, return_with_password boolean not null, returnIKO boolean not null, primary key (id));
create table EUMOWY.PROCESS (id number(19,0) not null, version number(19,0) not null, calc_number varchar2(255 char), client_id number(19,0), date_created timestamp not null, last_updated timestamp not null, ph_first_name varchar2(255 char), ph_number varchar2(255 char), ph_surname varchar2(255 char), sale_section varchar2(255 char), status varchar2(255 char), primary key (id));
create table EUMOWY.PROCESS_DATA (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char), process_id number(19,0), value varchar2(255 char), data_idx number(10,0), primary key (id));
create table EUMOWY.SIGNATURE (id number(19,0) not null, version number(19,0) not null, active number(1,0), management_subscription1 varchar(255), management_subscription2 varchar(255), subscription_page_number integer, subscriptionx integer, subscriptionxscale integer, subscriptiony integer, subscriptionyscale integer, template_path varchar(255), name varchar2(255 char) unique, primary key (id));
create table EUMOWY.SIGNATURE_PANEL (id number(19,0) not null, version number(19,0) not null, panel_id number(19,0), signature_id number(19,0), primary key (id));
create table EUMOWY.SUBSCRIPTION (id number(19,0) not null, version number(19,0) not null, content long, primary key (id));
create table EUMOWY.process_activity (process_activities_id number(19,0), activity_id number(19,0), activities_idx number(10,0));
create table EUMOWY.process_signature (process_signatures_id number(19,0), signature_id number(19,0), signatures_idx number(10,0));
create table EUMOWY.process_subscription (process_subscriptions_id number(19,0), subscription_id number(19,0), subscriptions_idx number(10,0));

-- CONSTRAINTS
-- TODO do poprawy nazwy FK
alter table EUMOWY.ACTIVITY_SIGNATURES add constraint FK19F8ADEBC1A12403 foreign key (activity_id) references EUMOWY.ACTIVITY;
alter table EUMOWY.ACTIVITY_SIGNATURES add constraint FK19F8ADEBED846B31 foreign key (signature_id) references EUMOWY.SIGNATURE;
alter table EUMOWY.ATTACHMENT add constraint FKA7E14523C7962D91 foreign key (process_id) references EUMOWY.PROCESS;
alter table EUMOWY.CALCFIELD_SIGNATURE add constraint FK5E9E7C7EF3FEB546 foreign key (calc_field_id) references EUMOWY.CALCFIELD;
alter table EUMOWY.CALCFIELD_SIGNATURE add constraint FK5E9E7C7EED846B31 foreign key (signature_id) references EUMOWY.SIGNATURE;
alter table EUMOWY.DOCUMENT add constraint FK6202C11BC7962D91 foreign key (process_id) references EUMOWY.PROCESS;
alter table EUMOWY.DOCUMENT_CONTENT add constraint FK6AFBDD3553CCC01F foreign key (document_id) references EUMOWY.DOCUMENT;
alter table EUMOWY.POINT add constraint FK48C5D70C7962D91 foreign key (process_id) references EUMOWY.PROCESS;
alter table EUMOWY.POINT_DETAILS add constraint FK870412537E3837FB foreign key (point_id) references EUMOWY.POINT;
alter table EUMOWY.POS add constraint FK136347E3837FB foreign key (point_id) references EUMOWY.POINT;
alter table EUMOWY.POS_DETAILS add constraint FK1085E7176EE8813B foreign key (pos_id) references EUMOWY.POS;
alter table EUMOWY.PROCESS add constraint FK1858AA4FD030B0C3 foreign key (client_id) references EUMOWY.CLIENT;
alter table EUMOWY.PROCESS_DATA add constraint FK2AB0F9AC7962D91 foreign key (process_id) references EUMOWY.PROCESS;
alter table EUMOWY.SIGNATURE_PANEL add constraint FK688D4B7D84182B31 foreign key (panel_id) references EUMOWY.PANEL;
alter table EUMOWY.SIGNATURE_PANEL add constraint FK688D4B7DED846B31 foreign key (signature_id) references EUMOWY.SIGNATURE;
alter table EUMOWY.process_activity add constraint FKD3BAD0D9C1A12403 foreign key (activity_id) references EUMOWY.ACTIVITY;
alter table EUMOWY.process_signature add constraint FKD76A742EED846B31 foreign key (signature_id) references EUMOWY.SIGNATURE;
alter table EUMOWY.process_subscription add constraint FK992D41E74E3344C3 foreign key (subscription_id) references EUMOWY.SUBSCRIPTION;

-- SEQUENCES
create sequence EUMOWY.ACTIVITY_SEQ;
create sequence EUMOWY.ACTIVITY_SIGNATURES_SEQ;
create sequence EUMOWY.ADM_U_WEB_SEQ;
create sequence EUMOWY.ATTACHMENT_CONTENT_SEQ;
create sequence EUMOWY.ATTACHMENT_SEQ;
create sequence EUMOWY.CALCFIELD_SEQ;
create sequence EUMOWY.CALCFIELD_SIGNATURE_SEQ;
create sequence EUMOWY.CLIENT_SEQ;
create sequence EUMOWY.DOCUMENT_SEQ;
create sequence EUMOWY.DOCUMENT_CONTENT_SEQ;
create sequence EUMOWY.EMAIL_TEMPLATES_SEQ;
create sequence EUMOWY.PANEL_SEQ;
create sequence EUMOWY.POINT_DETAILS_SEQ;
create sequence EUMOWY.POINT_SEQ;
create sequence EUMOWY.POS_DETAILS_SEQ;
create sequence EUMOWY.POS_SEQ;
create sequence EUMOWY.PROCESS_SEQ;
create sequence EUMOWY.PROCESS_DATA_SEQ;
create sequence EUMOWY.SIGNATURE_PANEL_SEQ;
create sequence EUMOWY.SIGNATURE_SEQ;
create sequence EUMOWY.SUBSCRIPTION_SEQ;
create sequence EUMOWY.APP_PARAMETERS_SEQ;
