-- CREATE TABLES
create table EUMOWY.APP_PARAMETERS (id number(19,0) not null, name varchar2(255 char) unique, value varchar2(512 char), primary key (id));
create table EUMOWY.ACTIVITY (id number(19,0) not null, version number(19,0) not null, code varchar2(255 char) unique, numer_pozycji number(10,0) unique, primary key (id));
create table EUMOWY.ACTIVITY_SIGNATURES (id number(19,0) not null, version number(19,0) not null, activity_id number(19,0), mandatory number(1,0) not null, number_of_list number(10,0), signature_id number(19,0), primary key (id));
create table EUMOWY.ATTACHMENT (id number(19,0) not null, date_created timestamp not null, filename varchar2(255 char), last_updated timestamp not null, process_id number(19,0), attachments_idx number(10,0), primary key (id));
create table EUMOWY.ATTACHMENT_CONTENT (id integer not null, version integer not null, attachment_id integer not null unique, content BLOB not null, primary key (id));
create table EUMOWY.CALCFIELD (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) unique, primary key (id));
create table EUMOWY.CALCFIELD_SIGNATURE (id number(19,0) not null, version number(19,0) not null, calc_field_id number(19,0), signature_id number(19,0), primary key (id));
create table EUMOWY.CLIENT (id number(19,0) not null, version number(19,0) not null, cbd_id varchar2(255 char) unique, name varchar2(255 char) unique, nip varchar2(255 char) unique, primary key (id));
create table EUMOWY.DOCUMENT (id number(19,0) not null, version number(19,0) not null, date_created timestamp, last_updated timestamp, name varchar2(255 char) not null, pages_count number(10,0) not null, process_id number(19,0), signature_id number(19,0), documents_idx number(10,0), primary key (id));
create table EUMOWY.DOCUMENT_CONTENT (id number(19,0) not null, version number(19,0) not null, content blob not null, document_id number(19,0) not null unique, primary key (id));
create table EUMOWY.EMAIL_TEMPLATES (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char), recipent varchar2(255 char), sender varchar2(255 char), primary key (id));
create table EUMOWY.PANEL (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) unique, order_no number(10,0), primary key (id));
create table EUMOWY.POINT (id number(19,0) not null, version number(19,0) not null, cbd_id number(10,0) not null, postal_code varchar2(255 char) not null, city varchar2(255 char) not null, nip varchar2(255 char) not null, home_number number(10,0) not null, flat_number number(10,0) not null, post_office varchar2(255 char) not null, process_id number(19,0), street varchar2(255 char) not null, primary key (id));
create table EUMOWY.POINT_DETAILS (id number(19,0) not null, version number(19,0) not null, bank_name varchar2(255 char) not null, contact_addr_streettype varchar2(255 char) not null, mcc_code varchar2(255 char) not null, contact_at_point_email varchar2(255 char) not null, contact_at_point_fax varchar2(255 char) not null, contact_at_point_firstname varchar2(255 char) not null, contact_at_point_lastname varchar2(255 char) not null, contact_at_point_mobilephone varchar2(255 char) not null, contact_at_point_phone varchar2(255 char) not null, contact_addr_postalcode varchar2(255 char) not null, contact_addr_home_number number(10,0) not null, contact_addr_flat_number number(10,0) not null, contact_addr_post_office varchar2(255 char) not null, contact_addr_street varchar2(255 char) not null, contact_addr_city varchar2(255 char) not null, name_print_posterminal varchar2(255 char) not null, name_search_engine varchar2(255 char) not null, nip varchar2(255 char) not null, bank_account_number varchar2(255 char) not null, business_care number(19,2) not null, service_care1 number(19,2) not null, service_care2 number(19,2) not null, service_care3 number(19,2) not null, ph_gain number(19,2) not null, point_id number(19,0) not null unique, bussiness_type_in_practice varchar2(255 char) not null, terminal_count number(10,0) not null, print_addr_postal_code varchar2(255 char) not null, print_otherdata_terminal1 varchar2(255 char) not null, print_otherdata_terminal2 varchar2(255 char) not null, print_addr_city varchar2(255 char) not null, print_addr_home_number number(10,0) not null, print_addr_flat_number number(10,0) not null, print_addr_post_office varchar2(255 char) not null, print_addr_street varchar2(255 char) not null, print_addressstreet_type varchar2(255 char) not null, primary key (id));
create table EUMOWY.POS (id number(19,0) not null, version number(19,0) not null, is_selected number(1,0) not null, date_to timestamp not null, date_from timestamp not null, pos_set_number number(10,0) not null, point_id number(19,0), price_count number(19,2) not null, primary key (id));
create table EUMOWY.POS_DETAILS (id number(19,0) not null, version number(19,0) not null, statdevice_ip varchar2(255 char) not null, set_analysis number(1,0) not null, base_count number(10,0) not null, noreturnfunction number(1,0) not null, statdevice_gateway varchar2(255 char) not null, card_reader_price number(19,2) not null, card_reader_count number(10,0) not null, card_reader_type varchar2(255 char) not null, dialup_price number(19,2) not null, dialup_count number(10,0) not null, dialup_pp_price number(19,2) not null, dialup_pp_count number(10,0) not null, dialup_type varchar2(255 char) not null, gprs_price number(19,2) not null, gprs_count number(10,0) not null, gprs_pp_price number(19,2) not null, gprs_pp_count number(10,0) not null, gprs_type varchar2(255 char) not null, dynamicdevicesupp_name varchar2(255 char) not null, statdevicesupp_contactname varchar2(255 char) not null, other_additional_device varchar2(255 char) not null, otheradditionaldevice_price number(19,2) not null, otheradditionaldevice_gprs number(1,0) not null, otheradditionaldevice_count number(10,0) not null, otheradditionaldevice_ssl number(1,0) not null, otheradditionaldevice_type varchar2(255 char) not null, cashmachine_systemintegration number(1,0) not null, gift_card number(1,0) not null, dynamicdevicesupp_contact varchar2(255 char) not null, statdevicesupp_contact varchar2(255 char) not null, log_beforeeverytransaction number(1,0) not null, log_everychange number(1,0) not null, statdevice_mask varchar2(255 char) not null, tip1 number(1,0) not null, dynamicdevicesupp_surname varchar2(255 char) not null, statdevicesupp_contactsurname varchar2(255 char) not null, pin_pad_price number(19,2) not null, pin_pad_count number(10,0) not null, pin_pad_type varchar2(255 char) not null, planned_installation_date timestamp not null, pos_id number(19,0) not null unique, preauthorization number(1,0) not null, router_price number(19,2) not null, router_count number(10,0) not null, router_type varchar2(255 char) not null, ssl_price number(19,2) not null, ssl_count number(10,0) not null, ssl_pp_price number(19,2) not null, ssl_pp_count number(10,0) not null, ssl_type varchar2(255 char) not null, tele_kodzik number(1,0) not null, tele_pompka number(1,0) not null, additional_notes varchar2(255 char) not null, vpn_price number(19,2) not null, vpn_count number(10,0) not null, vpn_pp_price number(19,2) not null, vpn_pp_count number(10,0) not null, vpn_type varchar2(255 char) not null, wifi_price number(19,2) not null, wifi_count number(10,0) not null, wifi_pp_price number(19,2) not null, wifi_pp_count number(10,0) not null, wifi_type varchar2(255 char) not null, day_close_to timestamp not null, day_close_from timestamp not null, return_with_password number(1,0) not null, returnIKO number(1,0) not null, primary key (id));
create table EUMOWY.PROCESS (id number(19,0) not null, version number(19,0) not null, calc_number varchar2(255 char), client_id number(19,0), date_created timestamp not null, last_updated timestamp not null, ph_first_name varchar2(255 char), ph_number varchar2(255 char), ph_surname varchar2(255 char), ph_email varchar2(255 char), sale_section varchar2(255 char), status varchar2(255 char), notes_to_coa varchar2(1000 char), notes_to_zrd varchar2(300 char), primary key (id));
create table EUMOWY.PROCESS_DATA (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char), process_id number(19,0), value varchar2(255 char), data_idx number(10,0), primary key (id));
create table EUMOWY.SIGNATURE (id number(19,0) not null, version number(19,0) not null, active number(1,0) not null, management_subscription1 varchar2(255 char) not null, management_subscription2 varchar2(255 char) not null, name varchar2(255 char) not null unique, ph_subscription_page_number number(10,0), ph_subscriptionx number(10,0), ph_subscriptiony number(10,0), subscription_page_number number(10,0), subscriptionx number(10,0), subscriptiony number(10,0), template_path varchar2(255 char) not null, primary key (id));
create table EUMOWY.SIGNATURE_PANEL (id number(19,0) not null, version number(19,0) not null, panel_id number(19,0), signature_id number(19,0), primary key (id));
create table EUMOWY.SUBSCRIPTION (id number(19,0) not null, version number(19,0) not null, content long not null, name varchar2(255 char) not null, person_role varchar2(255 char), process_id number(19,0), sign_date timestamp not null, surname varchar2(255 char) not null, primary key (id));
create table EUMOWY.PROCESS_ACTIVITY (process_activities_id number(19,0), activity_id number(19,0), activities_idx number(10,0));
create table EUMOWY.PROCESS_SIGNATURE (process_signatures_id number(19,0), signature_id number(19,0), signatures_idx number(10,0));
create table EUMOWY.PROCCESS_SUBSCRIPTION (process_subscriptions_id number(19,0), subscription_id number(19,0), subscriptions_idx number(10,0));

-- CONSTRAINTS
-- TODO do poprawy nazwy FK
alter table EUMOWY.ACTIVITY_SIGNATURES add constraint ACTIVITY_SIGNATURES_ACT_ID_FK foreign key (activity_id) references EUMOWY.ACTIVITY;
alter table EUMOWY.ACTIVITY_SIGNATURES add constraint ACTIVITY_SIGNATURES_SIGN_ID_FK foreign key (signature_id) references EUMOWY.SIGNATURE;
alter table EUMOWY.ATTACHMENT add constraint ATTACHMENT_PROCESS_ID_FK foreign key (process_id) references EUMOWY.PROCESS;
alter table EUMOWY.CALCFIELD_SIGNATURE add constraint CALCFIELD_SIGNATURE_CLC_ID_FK foreign key (calc_field_id) references EUMOWY.CALCFIELD;
alter table EUMOWY.CALCFIELD_SIGNATURE add constraint CALCFIELD_SIGNATURE_SIG_ID foreign key (signature_id) references EUMOWY.SIGNATURE;
alter table EUMOWY.DOCUMENT add constraint DOCUMENT_SIGNATURE_ID_FK foreign key (signature_id) references EUMOWY.SIGNATURE;
alter table EUMOWY.DOCUMENT add constraint DOCUMENT_PROCESS_ID_FK foreign key (process_id) references EUMOWY.PROCESS;
alter table EUMOWY.DOCUMENT_CONTENT add constraint DOCUMENT_CONTENT_DOC_ID_FK foreign key (document_id) references EUMOWY.DOCUMENT;
alter table EUMOWY.POINT add constraint POINT_PROCESS_ID_FK foreign key (process_id) references EUMOWY.PROCESS;
alter table EUMOWY.POINT_DETAILS add constraint POINT_DETAILS_POINT_ID_FK foreign key (point_id) references EUMOWY.POINT;
alter table EUMOWY.POS add constraint POS_POINT_ID_FK foreign key (point_id) references EUMOWY.POINT;
alter table EUMOWY.POS_DETAILS add constraint POS_DETAILS_POS_ID_FK foreign key (pos_id) references EUMOWY.POS;
alter table EUMOWY.PROCESS add constraint PROCESS_CLIENT_ID_FK foreign key (client_id) references EUMOWY.CLIENT;
alter table EUMOWY.PROCESS_DATA add constraint PROCESS_DATA_PROCESS_ID_FK foreign key (process_id) references EUMOWY.PROCESS;
alter table EUMOWY.SIGNATURE_PANEL add constraint SIGNATURE_PANEL_PANEL_ID_FK foreign key (panel_id) references EUMOWY.PANEL;
alter table EUMOWY.SIGNATURE_PANEL add constraint SIGNATURE_PANEL_SIGN_ID foreign key (signature_id) references EUMOWY.SIGNATURE;
alter table EUMOWY.PROCESS_ACTIVITY add constraint PROCESS_ACTIVITY_ACT_ID_FK foreign key (activity_id) references EUMOWY.ACTIVITY;
alter table EUMOWY.PROCESS_ACTIVITY add constraint PROCESS_ACTIVITY_PROCESS_ID_FK foreign key (process_activities_id) references EUMOWY.PROCESS;
alter table EUMOWY.PROCESS_SIGNATURE add constraint PROCESS_SIGNATURE_SIGN_ID_FK foreign key (signature_id) references EUMOWY.SIGNATURE;
alter table EUMOWY.PROCESS_SIGNATURE add constraint PROCESS_SIGNATURE_PRO_ID_FK foreign key (process_signatures_id) references EUMOWY.PROCESS;
alter table EUMOWY.PROCESS_SUBSCRIPTION add constraint PROCCESS_SUBSCRIPTION_SU_ID_FK foreign key (subscription_id) references EUMOWY.SUBSCRIPTION;
alter table EUMOWY.PROCESS_SUBSCRIPTION add constraint PROCCESS_SUBSCRIPTION_PR_ID_FK foreign key (process_subscriptions_id) references EUMOWY.PROCESS;

-- SEQUENCES
create sequence EUMOWY.ACTIVITY_SEQ;
create sequence EUMOWY.ACTIVITY_SIGNATURES_SEQ;
create sequence EUMOWY.ADM_U_WEB_SEQ;
create sequence EUMOWY.ATTACHMENT_CONTENT_SEQ;
create sequence EUMOWY.ATTACHMENT_SEQ;
create sequence EUMOWY.CALCFIELD_SEQ;
create sequence EUMOWY.CALCFIELD_SIGNATURE_SEQ;
create sequence EUMOWY.CLIENT_SEQ;
create sequence EUMOWY.DOCUMENT_SEQ;
create sequence EUMOWY.DOCUMENT_CONTENT_SEQ;
create sequence EUMOWY.EMAIL_TEMPLATES_SEQ;
create sequence EUMOWY.PANEL_SEQ;
create sequence EUMOWY.POINT_DETAILS_SEQ;
create sequence EUMOWY.POINT_SEQ;
create sequence EUMOWY.POS_DETAILS_SEQ;
create sequence EUMOWY.POS_SEQ;
create sequence EUMOWY.PROCESS_SEQ;
create sequence EUMOWY.PROCESS_DATA_SEQ;
create sequence EUMOWY.SIGNATURE_PANEL_SEQ;
create sequence EUMOWY.SIGNATURE_SEQ;
create sequence EUMOWY.SUBSCRIPTION_SEQ;
create sequence EUMOWY.APP_PARAMETERS_SEQ;
