ALTER TABLE EUMOWY.PROCESS ADD PH_MOBILE_PHONE varchar(20) NULL;
ALTER TABLE EUMOWY.PROCESS ADD PH_DOCS_SIGNING_CODE varchar(8) NULL;
ALTER TABLE EUMOWY.REPRESENTATIVE ADD DOCS_SIGNING_CODE varchar(8) NULL;
ALTER TABLE EUMOWY.SUBSCRIPTION ADD SIGNING_CODE varchar(8) NULL;
