cbd.db.url=jdbc:oracle:thin:@192.168.3.162:1521:cbd
cbd.db.user=cbd_web
cbd.db.password=GLcbd_web2$
cbd.db.driver=oracle.jdbc.OracleDriver
cbd.db.dialect=org.hibernate.dialect.Oracle10gDialect
cbd.sync.default.uri=http://localhost:8080/webs/cbdSync
cbd.gov.sync.default.uri=http://localhost:8080/webs/govSync
microBisnode.service.uri=http://10.9.23.29:8114/bisnode/
microLDAP.service.uri=http://uat-eumowy.apreel.net:8080/microLDAP/
microLDAP.service.domain=tescik
microLDAP.service.groups=gr_EUM
microLDAP.service.department=gr_EUM
eumowy.cbd.sync.default.uri=http://localhost:8080/e-umowy-sync-ws/acceptUmowa/
smsClient.uri=http://10.9.23.94:8101
smsClient.sender=ESERVICE
smsClient.source=EUMOWY
smsClient.partner=true
