ALTER TABLE EUMOWY.POINT_DETAILS
    ADD IS_ACCEPTED_CARD_TRANSACTIONS number(1,0);

ALTER TABLE EUMOWY.POINT_DETAILS
    ADD IS_PRIVATE_APARTMENT number(1,0);

ALTER TABLE EUMOWY.POINT_DETAILS
    ADD IS_ACCEPTED_PREPAYMENTS number(1,0);

ALTER TABLE EUMOWY.POINT_DETAILS
    ADD MONTHLY_CASH_TURNOVER varchar2(240 CHAR) NULL;

ALTER TABLE EUMOWY.POINT_DETAILS
    ADD MONTHLY_TURNOVER_INSTITUTION varchar2(240 CHAR) NULL;

ALTER TABLE EUMOWY.POINT_DETAILS
    ADD AVERAGE_BILL varchar2(240 CHAR) NULL;

ALTER TABLE EUMOWY.POINT_DETAILS
    ADD HIGHEST_CASH_TRANSACTION varchar2(240 CHAR) NULL;

ALTER TABLE EUMOWY.POINT_DETAILS
    ADD NUMBER_OF_DAILY_TRANSACTIONS varchar2(240 CHAR) NULL;

ALTER TABLE EUMOWY.POINT_DETAILS
    ADD PERCENTAGE_OF_PREPAYMENTS varchar2(240 CHAR) NULL;

ALTER TABLE EUMOWY.POINT_DETAILS
    ADD AVERAGE_DELIVERY_TIME varchar2(240 CHAR) NULL;

ALTER TABLE EUMOWY.POINT_DETAILS
    ADD MAXIMUM_DELIVERY_TIME varchar2(240 CHAR) NULL;

UPDATE eumowy.signature s SET show_on_preview = 1 WHERE id = 3;

