import { ProcessListItem, ProcessStatus, formatProcessDate } from './process-list.models';

interface MockProcessSeed extends Omit<ProcessListItem, 'lastUpdated' | 'dateCreated'> {
  lastUpdatedDaysAgo: number;
  dateCreatedDaysAgo: number;
}

const PROCESS_SEEDS: MockProcessSeed[] = [
  {
    id: 1018,
    phNumber: 'PH/2026/00118',
    nip: '7789901122',
    clientName: 'Nova Retail Sp. z o.o.',
    activity: 'Nowa umowa',
    salesSegment: 'SMB',
    phEmail: 'adam.nowak@eservice.local',
    phName: 'Adam Nowak',
    status: 'WAITING',
    lastUpdatedDaysAgo: 1,
    dateCreatedDaysAgo: 8,
    documentsFormat: 'ELECTRONIC',
    notesFromCoa: 'Komplet dokumentów potwierdzony.',
    notesFromZrd: 'Weryfikacja końcowa.',
    observed: false,
  },
  {
    id: 1017,
    phNumber: 'PH/2026/00117',
    nip: '6654432211',
    clientName: 'Baltic Market SA',
    activity: 'Zmiana warunków',
    salesSegment: 'Enterprise',
    phEmail: 'ewa.krawczyk@eservice.local',
    phName: 'Ewa Krawczyk',
    status: 'WAITING',
    lastUpdatedDaysAgo: 2,
    dateCreatedDaysAgo: 9,
    documentsFormat: 'PAPER',
    notesFromCoa: 'Brak uwag.',
    notesFromZrd: 'Do akceptacji po rozmowie z PH.',
    observed: true,
  },
  {
    id: 1016,
    phNumber: 'PH/2026/00116',
    nip: '5219087744',
    clientName: 'Studio Zielona Mila',
    activity: 'Nowa umowa',
    salesSegment: 'Micro',
    phEmail: 'maria.wisniewska@eservice.local',
    phName: 'Maria Wiśniewska',
    status: 'WAITING',
    lastUpdatedDaysAgo: 3,
    dateCreatedDaysAgo: 10,
    documentsFormat: 'ELECTRONIC',
    notesFromCoa: 'Oczekuje na potwierdzenie adresu.',
    notesFromZrd: 'Sprawdzić dokument KRS.',
    observed: false,
  },
  {
    id: 1015,
    phNumber: 'PH/2026/00115',
    nip: '9021453321',
    clientName: 'Centrum Medyczne Vita',
    activity: 'Wymiana terminali',
    salesSegment: 'Healthcare',
    phEmail: 'piotr.mazur@eservice.local',
    phName: 'Piotr Mazur',
    status: 'WAITING',
    lastUpdatedDaysAgo: 4,
    dateCreatedDaysAgo: 12,
    documentsFormat: 'TEMPLATE',
    notesFromCoa: 'Załączniki zgodne z checklistą.',
    notesFromZrd: 'Gotowe do publikacji.',
    observed: false,
  },
  {
    id: 1014,
    phNumber: 'PH/2026/00114',
    nip: '3344556677',
    clientName: 'Księgarnia Polaris',
    activity: 'Nowa umowa',
    salesSegment: 'SMB',
    phEmail: 'anna.kaczmarek@eservice.local',
    phName: 'Anna Kaczmarek',
    status: 'WAITING',
    lastUpdatedDaysAgo: 5,
    dateCreatedDaysAgo: 13,
    documentsFormat: 'ELECTRONIC',
    notesFromCoa: 'Zweryfikowano rachunek bankowy.',
    notesFromZrd: 'Bez uwag.',
    observed: false,
  },
  {
    id: 1013,
    phNumber: 'PH/2026/00113',
    nip: '4455667788',
    clientName: 'Hotel Rubikon',
    activity: 'Aneks do umowy',
    salesSegment: 'Hospitality',
    phEmail: 'lukasz.dabrowski@eservice.local',
    phName: 'Łukasz Dąbrowski',
    status: 'WAITING',
    lastUpdatedDaysAgo: 6,
    dateCreatedDaysAgo: 15,
    documentsFormat: 'PAPER',
    notesFromCoa: 'Wymagana korekta nazwy punktu.',
    notesFromZrd: 'Oczekiwanie na telefon od klienta.',
    observed: false,
  },
  {
    id: 1012,
    phNumber: 'PH/2026/00112',
    nip: '1234567890',
    clientName: 'Firma Helios Sp. z o.o.',
    activity: 'Nowa umowa',
    salesSegment: 'SMB',
    phEmail: 'karolina.wojcik@eservice.local',
    phName: 'Karolina Wójcik',
    status: 'WAITING',
    lastUpdatedDaysAgo: 7,
    dateCreatedDaysAgo: 16,
    documentsFormat: 'ELECTRONIC',
    notesFromCoa: 'Aktywność potwierdzona w CBD.',
    notesFromZrd: 'Priorytet operatora ZRD.',
    observed: true,
  },
  {
    id: 1011,
    phNumber: 'PH/2026/00111',
    nip: '2233445566',
    clientName: 'Bio Farma Partner',
    activity: 'Zmiana danych klienta',
    salesSegment: 'Healthcare',
    phEmail: 'pawel.jaworski@eservice.local',
    phName: 'Paweł Jaworski',
    status: 'WAITING',
    lastUpdatedDaysAgo: 8,
    dateCreatedDaysAgo: 17,
    documentsFormat: 'ELECTRONIC',
    notesFromCoa: 'Wniosek podpisany elektronicznie.',
    notesFromZrd: 'Wstrzymać do czasu finalnej kontroli.',
    observed: false,
  },
  {
    id: 1010,
    phNumber: 'PH/2026/00110',
    nip: '9988776655',
    clientName: 'Market Orion',
    activity: 'Nowa umowa',
    salesSegment: 'Retail',
    phEmail: 'justyna.sikora@eservice.local',
    phName: 'Justyna Sikora',
    status: 'WAITING',
    lastUpdatedDaysAgo: 9,
    dateCreatedDaysAgo: 18,
    documentsFormat: 'PAPER',
    notesFromCoa: 'Wszystkie pola uzupełnione.',
    notesFromZrd: 'Do szybkiej akceptacji.',
    observed: false,
  },
  {
    id: 1009,
    phNumber: 'PH/2026/00109',
    nip: '5647382910',
    clientName: 'Galeria Słoneczna',
    activity: 'Rozszerzenie usług',
    salesSegment: 'Retail',
    phEmail: 'tomasz.lewandowski@eservice.local',
    phName: 'Tomasz Lewandowski',
    status: 'WAITING',
    lastUpdatedDaysAgo: 10,
    dateCreatedDaysAgo: 19,
    documentsFormat: 'TEMPLATE',
    notesFromCoa: 'Konieczne potwierdzenie segmentu sprzedaży.',
    notesFromZrd: 'Dodać numer telefonu kontaktowego.',
    observed: false,
  },
  {
    id: 1008,
    phNumber: 'PH/2026/00108',
    nip: '7812459036',
    clientName: 'Transport Plus',
    activity: 'Nowa umowa',
    salesSegment: 'Logistics',
    phEmail: 'agata.krupa@eservice.local',
    phName: 'Agata Krupa',
    status: 'WAITING',
    lastUpdatedDaysAgo: 11,
    dateCreatedDaysAgo: 20,
    documentsFormat: 'ELECTRONIC',
    notesFromCoa: 'Zweryfikowano tożsamość reprezentanta.',
    notesFromZrd: 'Sprawa monitorowana.',
    observed: true,
  },
  {
    id: 1007,
    phNumber: 'PH/2026/00107',
    nip: '7024681359',
    clientName: 'Restauracja Saffron',
    activity: 'Przedłużenie umowy',
    salesSegment: 'Hospitality',
    phEmail: 'michal.zawadzki@eservice.local',
    phName: 'Michał Zawadzki',
    status: 'WAITING',
    lastUpdatedDaysAgo: 12,
    dateCreatedDaysAgo: 22,
    documentsFormat: 'PAPER',
    notesFromCoa: 'Dołączyć pełnomocnictwo.',
    notesFromZrd: 'Czeka na poprawkę od PH.',
    observed: false,
  },
  {
    id: 1006,
    phNumber: 'PH/2026/00106',
    nip: '1928374650',
    clientName: 'Auto Serwis Quattro',
    activity: 'Nowa umowa',
    salesSegment: 'Automotive',
    phEmail: 'ola.piotrowska@eservice.local',
    phName: 'Ola Piotrowska',
    status: 'WAITING',
    lastUpdatedDaysAgo: 13,
    dateCreatedDaysAgo: 23,
    documentsFormat: 'ELECTRONIC',
    notesFromCoa: 'Brak zastrzeżeń.',
    notesFromZrd: 'Weryfikacja dokumentów zakończona.',
    observed: false,
  },
  {
    id: 1005,
    phNumber: 'PH/2026/00105',
    nip: '6655443322',
    clientName: 'Studio Foto Miga',
    activity: 'Aneks do umowy',
    salesSegment: 'Services',
    phEmail: 'damian.janik@eservice.local',
    phName: 'Damian Janik',
    status: 'WAITING',
    lastUpdatedDaysAgo: 14,
    dateCreatedDaysAgo: 25,
    documentsFormat: 'TEMPLATE',
    notesFromCoa: 'Sprawdzić podpis reprezentanta.',
    notesFromZrd: 'Wymaga finalnej decyzji.',
    observed: false,
  },
  {
    id: 1004,
    phNumber: 'PH/2026/00104',
    nip: '1122334455',
    clientName: 'Eco Tech Polska',
    activity: 'Nowa umowa',
    salesSegment: 'Technology',
    phEmail: 'martyna.olszewska@eservice.local',
    phName: 'Martyna Olszewska',
    status: 'NEW',
    lastUpdatedDaysAgo: 4,
    dateCreatedDaysAgo: 5,
    documentsFormat: 'ELECTRONIC',
    notesFromCoa: 'Formularz w edycji.',
    notesFromZrd: 'Brak działań.',
    observed: false,
  },
  {
    id: 1003,
    phNumber: 'PH/2026/00103',
    nip: '8877665544',
    clientName: 'Moneta Finanse',
    activity: 'Zmiana danych klienta',
    salesSegment: 'Finance',
    phEmail: 'aleksandra.kowal@eservice.local',
    phName: 'Aleksandra Kowal',
    status: 'WAIT_FOR_SUBSCRIPTION',
    lastUpdatedDaysAgo: 16,
    dateCreatedDaysAgo: 21,
    documentsFormat: 'PAPER',
    notesFromCoa: 'Oczekuje na podpis klienta.',
    notesFromZrd: 'Monitorować termin podpisu.',
    observed: false,
  },
  {
    id: 1002,
    phNumber: 'PH/2026/00102',
    nip: '5566778899',
    clientName: 'Delikatesy Mango',
    activity: 'Nowa umowa',
    salesSegment: 'Retail',
    phEmail: 'robert.frankowski@eservice.local',
    phName: 'Robert Frankowski',
    status: 'WAIT_FOR_SUBSCRIPTION_PAPER_VERSION',
    lastUpdatedDaysAgo: 17,
    dateCreatedDaysAgo: 24,
    documentsFormat: 'PAPER',
    notesFromCoa: 'Wysłano wersję papierową.',
    notesFromZrd: 'Oczekiwanie na przesyłkę.',
    observed: false,
  },
  {
    id: 1001,
    phNumber: 'PH/2026/00101',
    nip: '4411223344',
    clientName: 'Dom i Ogród Lider',
    activity: 'Rozszerzenie usług',
    salesSegment: 'Retail',
    phEmail: 'kamil.szymanski@eservice.local',
    phName: 'Kamil Szymański',
    status: 'SUBSCRIPTIONS_DONE',
    lastUpdatedDaysAgo: 18,
    dateCreatedDaysAgo: 26,
    documentsFormat: 'ELECTRONIC',
    notesFromCoa: 'Podpisy kompletne.',
    notesFromZrd: 'Przekazać do kolejnego etapu.',
    observed: false,
  },
  {
    id: 1000,
    phNumber: 'PH/2026/00100',
    nip: '3311445566',
    clientName: 'Klinika Nova',
    activity: 'Przedłużenie umowy',
    salesSegment: 'Healthcare',
    phEmail: 'natalia.wozniak@eservice.local',
    phName: 'Natalia Woźniak',
    status: 'ACCEPTED',
    lastUpdatedDaysAgo: 19,
    dateCreatedDaysAgo: 27,
    documentsFormat: 'ELECTRONIC',
    notesFromCoa: 'Proces zaakceptowany.',
    notesFromZrd: 'Zamknięto bez uwag.',
    observed: false,
  },
  {
    id: 999,
    phNumber: 'PH/2026/00099',
    nip: '2200113344',
    clientName: 'Fabryka Smaku',
    activity: 'Nowa umowa',
    salesSegment: 'Hospitality',
    phEmail: 'sebastian.baran@eservice.local',
    phName: 'Sebastian Baran',
    status: 'CORRECTION',
    lastUpdatedDaysAgo: 20,
    dateCreatedDaysAgo: 29,
    documentsFormat: 'TEMPLATE',
    notesFromCoa: 'Brak podpisu na jednym załączniku.',
    notesFromZrd: 'Wysłano do korekty.',
    observed: true,
  },
  {
    id: 998,
    phNumber: 'PH/2026/00098',
    nip: '9900112233',
    clientName: 'Kompas Travel',
    activity: 'Zmiana warunków',
    salesSegment: 'Travel',
    phEmail: 'izabela.adamska@eservice.local',
    phName: 'Izabela Adamska',
    status: 'REJECTED',
    lastUpdatedDaysAgo: 45,
    dateCreatedDaysAgo: 60,
    documentsFormat: 'PAPER',
    notesFromCoa: 'Niekompletna dokumentacja.',
    notesFromZrd: 'Proces odrzucony po analizie.',
    observed: false,
  },
];

export const MOCK_PROCESS_LIST_ITEMS: ProcessListItem[] = PROCESS_SEEDS.map((seed) => ({
  ...seed,
  lastUpdated: formatProcessDate(buildDateDaysAgo(seed.lastUpdatedDaysAgo)),
  dateCreated: formatProcessDate(buildDateDaysAgo(seed.dateCreatedDaysAgo)),
}));

export const MOCK_PROCESS_STATUS_VALUES: ProcessStatus[] = [
  'NEW',
  'REJECTED',
  'WAIT_FOR_SUBSCRIPTION',
  'WAIT_FOR_SUBSCRIPTION_PAPER_VERSION',
  'SUBSCRIPTIONS_DONE',
  'WAITING',
  'CORRECTION',
  'ACCEPTED',
];

function buildDateDaysAgo(daysAgo: number): Date {
  const date = new Date();
  date.setHours(12, 0, 0, 0);
  date.setDate(date.getDate() - daysAgo);

  return date;
}
