-- new fields for representatives & beneficiaries panels
ALTER TABLE EUMOWY.REPRESENTATIVE
ADD (
  CONTRACT_SIGNED NUMBER(1,0) NULL,
  LANDLINE_PHONE VARCHAR2(20) NULL,
  MOBILE_PHONE VARCHAR2(20) NULL,
  EMAIL VARCHAR2(80) NULL
);